export type ChangeType = "feat" | "fix" | "refactor" | "perf" | "docs" | "chore";

export const CHANGE_TYPE_LABELS: Record<ChangeType, string> = {
  feat: "Yeni Özellik",
  fix: "Düzeltme",
  refactor: "Yeniden Yapılandırma",
  perf: "Performans",
  docs: "Dokümantasyon",
  chore: "Bakım",
};

export const CHANGE_TYPE_COLORS: Record<ChangeType, string> = {
  feat: "#22c55e",
  fix: "#ef4444",
  refactor: "#a855f7",
  perf: "#f59e0b",
  docs: "#3b82f6",
  chore: "#6b7280",
};

export interface ChangeItem {
  type: ChangeType;
  text: string;
}

export interface ChangelogEntry {
  version: string;
  date: string;
  changes: (string | ChangeItem)[];
  summary?: string;
}

/** Yardımcı: string|ChangeItem → normalize */
export function normalizeChange(c: string | ChangeItem): ChangeItem {
  if (typeof c === "object") return c;
  if (c.startsWith("P1:") || c.startsWith("P2:") || c.startsWith("P3:")) return { type: "feat", text: c };
  const lower = c.toLowerCase();
  if (lower.includes("düzelt") || lower.includes("hata") || lower.includes("fix")) return { type: "fix", text: c };
  if (lower.includes("kaldır") || lower.includes("refactor") || lower.includes("taşındı") || lower.includes("birleştirildi") || lower.includes("sadeleştirildi")) return { type: "refactor", text: c };
  if (lower.includes("performans") || lower.includes("optimiz")) return { type: "perf", text: c };
  if (lower.includes("dokümant") || lower.includes("claude.md") || lower.includes("readme")) return { type: "docs", text: c };
  if (lower.includes("silindi") || lower.includes("temizlen") || lower.includes("lint")) return { type: "chore", text: c };
  return { type: "feat", text: c };
}

export const changelog: ChangelogEntry[] = [
  {
    version: "0.8.109",
    date: "2026-04-12",
    summary: "StatusBoard mobilde tek çerçeve içinde birleştirildi — tab'lar ve kart listesi artık aynı kutuda",
    changes: [
      { type: "refactor", text: "StatusBoard: mobilde dış çerçeve eklendi, tab'lar ve liste tek kutu içinde" },
      { type: "refactor", text: "StatusBoard: mobilde iç sütun bordürü kaldırıldı (çift çerçeve önlendi)" },
    ],
  },
  {
    version: "0.8.108",
    date: "2026-04-12",
    summary: "Takvimde sadece araç etkinliği olan günlere tıklayınca detay gösterilmiyordu — düzeltildi",
    changes: [
      { type: "fix", text: "Takvimde sadece araç etkinliği olan günlere tıklayınca detay paneli artık görünüyor" },
      { type: "fix", text: "Araç Etkinlikleri başlığı her durumda gösteriliyor (operasyon olmasa bile)" },
    ],
  },
  {
    version: "0.8.107",
    date: "2026-04-12",
    summary: "Takvim altındaki legend (açıklama) alanı kaldırıldı — bilişsel yük azaltıldı",
    changes: [
      { type: "refactor", text: "CalendarLegend bileşeni kaldırıldı — takvim hücreleri zaten renkli nokta + emoji gösteriyor, ek açıklama gereksiz" },
    ],
  },
  {
    version: "0.8.106",
    date: "2026-04-12",
    summary: "Sistem tutarsızlıkları giderildi: eksik SQL migration, dokümantasyon uyumsuzlukları düzeltildi",
    changes: [
      { type: "fix", text: "iha_info_bank CREATE TABLE ifadesi iha-schema.sql'e eklendi (eksikti)" },
      { type: "docs", text: "CLAUDE.md tablo sayısı 15→16 düzeltildi, iha_field_prep listeye eklendi" },
      { type: "docs", text: "MEMORY.md versiyon numarası ve Faz 7 planlanan versiyonlar güncellendi" },
      { type: "docs", text: "iha_field_prep soft-delete kararı belgelendi (ON DELETE CASCADE, soft delete gereksiz)" },
    ],
  },
  {
    version: "0.8.105",
    date: "2026-04-12",
    summary: "Operasyon formları tutarsızlık giderildi: saat alanları eklendi, konum bileşeni birleştirildi, kalan emoji'ler lucide'a çevrildi",
    changes: [
      { type: "feat", text: "OperationForm'a (düzenleme) startTime/endTime alanları eklendi. Başlangıç/Bitiş artık tarih+saat çifti olarak gösteriliyor — QuickCreateForm ile tutarlı" },
      { type: "refactor", text: "QuickCreateForm'daki LocationField (inline 60 satırlık sub-component) kaldırıldı, yerine OperationLocationSection kullanıldı. Artık hem yeni oluşturma hem düzenleme aynı konum bileşenini, aynı özet kartı, aynı manuel düzenleme accordion'unu kullanıyor" },
      { type: "refactor", text: "Konum butonundaki '📍' emoji → lucide MapPin SVG ikonu. Tüm cihazlarda tutarlı görünüm (TypeSelector'da v0.8.99'da yapılan emoji→SVG dönüşümünün devamı)" },
      { type: "chore", text: "QuickCreateForm import'ları sadeleşti: LocationPickerModal, FormSelect, BURSA_ILCELER, formatDistance kaldırıldı (hepsi OperationLocationSection içinde)" },
    ],
  },
  {
    version: "0.8.104",
    date: "2026-04-12",
    summary: "Harita filtre paneli: tam ekran modal kaldırıldı, yerine harita üzerinde küçük floating dropdown + checkbox'lar",
    changes: [
      { type: "refactor", text: "Harita filtre paneli Modal'dan floating dropdown'a çevrildi. Haritanın sağ üstünde küçük filtre ikonu, tıklayınca dropdown açılır — haritayı kapatmaz, arka plan görünür kalır" },
      { type: "refactor", text: "Katman toggle butonları checkbox'lara çevrildi: İlçe Sınırları, Mahalle Sınırları, Paftalar — anında uygulanır, 'Uygula' butonu gereksiz oldu" },
      { type: "refactor", text: "Gösterilen (Tümü/Operasyon/İzin) büyük butonları → iki checkbox: Operasyonlar ☑ / İzinler ☑. Daha minimal, boolean state (showOps/showPerms)" },
      { type: "refactor", text: "Durum filtre butonları küçük pill'lere küçültüldü (text-[10px]). Sıfırla linki altta" },
      { type: "chore", text: "Modal import MapTab'tan kaldırıldı, LayerFilter type kaldırıldı. MapFilterCheckbox helper component eklendi" },
    ],
  },
  {
    version: "0.8.103",
    date: "2026-04-12",
    summary: "Konum seçici haritasında Pafta/İlçe/Mahalle katmanları toggle ile açılabiliyor",
    changes: [
      { type: "feat", text: "LocationPicker (konum seçici) haritasında artık Harita sekmesindeki katmanlar gösterilebiliyor: Paftalar, İlçeler, Mahalleler — haritanın altında 3 küçük toggle buton ile açılıp kapanıyor" },
      { type: "refactor", text: "MapCanvas'a children prop eklendi — dışarıdan herhangi bir Leaflet katmanı inject edilebilir. Overlay layer'lar dynamic import (SSR-safe) ile yükleniyor" },
    ],
  },
  {
    version: "0.8.102",
    date: "2026-04-12",
    summary: "Uçuş İzinleri'nde toplu seçim + toplu durum değiştir + toplu sil + emoji filtre butonları metin oldu",
    changes: [
      { type: "feat", text: "Uçuş İzinleri sekmesine toplu seçim eklendi: 'Seç' butonu, her kart header'ında checkbox, Tümünü Seç / Hiçbirini Seçme, sticky action bar (Durumu Değiştir dropdown + Sil onaylı)" },
      { type: "refactor", text: "Durum filtre butonlarında emoji (⏳✅❌⏰) kaldırılıp metin yazıldı (Beklemede / Onaylandı / Reddedildi / Süresi Doldu). Mobilde ne olduğu artık okunabilir, emoji tutarsızlığı giderildi" },
    ],
  },
  {
    version: "0.8.101",
    date: "2026-04-12",
    summary: "Operasyonlar sekmesinde toplu seçim + toplu durum değiştirme + toplu silme özelliği eklendi",
    changes: [
      { type: "feat", text: "Operasyonlar sekmesinde 'Seç' butonu: tıklanınca toplu seçim modu aktif olur. Her operasyonun yanında checkbox belirir, Tümünü Seç / Hiçbirini Seçme ile hızlı seçim" },
      { type: "feat", text: "Mobilde OperationCard'a checkbox eklendi (sol üst). Seçili kartlar accent rengiyle vurgulanıyor. Masaüstünde DataTable'a checkbox column eklendi (header + row)" },
      { type: "feat", text: "Seçim yapılınca sticky action bar: 'N seçili' + 'Durumu Değiştir' dropdown (6 durum) + 'Sil (N)' butonu. Toplu silme onay diyaloğu ile korunuyor" },
      { type: "feat", text: "Toplu durum değiştirme: tıkla → Talep/Planlama/Saha/İşleme/Kontrol/Teslim seçenekleri → tüm seçili operasyonların durumu bir seferde değişir" },
      { type: "refactor", text: "DataTable generic component'e selectMode/selectedIds/onToggle/onToggleAll opsiyonel prop'ları eklendi — diğer tablolarda da kullanılabilir (envanter, personel vs.)" },
    ],
  },
  {
    version: "0.8.100",
    date: "2026-04-12",
    summary: "Genel Bakış daha minimal: başlık kaldırıldı, takvim hücre badge'leri max 3'e düşürüldü",
    changes: [
      { type: "refactor", text: "'Operasyon Yönetim Paneli' başlığı kaldırıldı — üstte zaten 'CBS İHA BİRİMİ' header'ı var, ikinci başlık gereksiz alan kaplıyordu. İçerik hemen StatusBoard ile başlıyor (~40px kazanç)" },
      { type: "refactor", text: "Takvim hücrelerinde mobilde max 3 operasyon dot'u gösteriliyor (önceden 4'tü). Fazlası '+N' olarak yazılıyor. Araç etkinlikleri de max 1. Toplam 3'ü aşarsa '+N' hesabı tüm öğeleri (operasyon + araç) kapsıyor — daha az görsel gürültü" },
    ],
  },
  {
    version: "0.8.99",
    date: "2026-04-11",
    summary: "Yeni Operasyon formu sadeleşti: 'İlçeyi elle gir' linki kalktı, Başlangıç/Bitiş TARİH alanları eklendi, operasyon tipi ikonları emoji yerine tutarlı Lucide SVG",
    changes: [
      { type: "refactor", text: "QuickCreateForm (Yeni Operasyon modalı) LocationField: 'İlçeyi elle gir' linki kaldırıldı. Haritadan konum seçilmediğinde ilçe dropdown'u direkt gösteriliyor — bir adım tasarrufu" },
      { type: "feat", text: "Yeni Operasyon formuna Başlangıç ve Bitiş TARİH alanları eklendi (önceden sadece saat vardı). Başlangıç tarihi değişince bitiş tarihi otomatik güncellenir (eğer daha eski bir tarih kalmışsa)" },
      { type: "refactor", text: "Operasyon tipi ikonları (İHA/LİDAR, Ortofoto/Oblik/360°/El Tarama/Araç Tarama) emoji yerine Lucide SVG'ye çevrildi. Emoji'ler telefon modeline göre farklı render oluyordu, artık tüm cihazlarda tutarlı görünüyor" },
      { type: "refactor", text: "types/iha.ts MAIN_CATEGORIES/SUB_CATEGORIES: icon alanı (emoji string) kaldırıldı. UI ikonları config/icons.ts'teki yeni MAIN_CATEGORY_ICONS + OP_SUBTYPE_ICONS mapping'lerinden geliyor (lucide-react)" },
      { type: "chore", text: "Icon mapping'leri: MAIN_CATEGORY_ICONS (Plane/Radar), OP_SUBTYPE_ICONS (Map/Triangle/Globe/Radar/Car). TypeSelector.tsx render güncellendi" },
    ],
  },
  {
    version: "0.8.98",
    date: "2026-04-11",
    summary: "StatusBoard tüm sütunlarda 5 kart limit + çoklu pafta tespiti (poligon için) + konum özet kartında pafta gösterimi",
    changes: [
      { type: "refactor", text: "StatusBoard'da DONE_LIMIT (sadece YAPILDI için 15'ti) kaldırıldı, yerine tüm sütunlar için COLUMN_LIMIT=5. YAPILACAK/YAPILIYOR/YAPILDI hepsinde artık max 5 kart görünüyor, fazlası 'Tümünü gör (N)' butonu ile Operasyonlar sekmesine yönlendiriyor" },
      { type: "refactor", text: "StatusBoard prop adı onViewAllDone → onViewAll olarak değişti (artık sadece YAPILDI için değil, tüm sütunlar için çalışıyor). IhaDashboard ve IhaBirimiContainer prop zinciri güncellendi" },
      { type: "feat", text: "LocationPicker'da pafta tespiti çoklu hale getirildi: poligon için tüm köşe noktalarının + centroid'in paftaları unique set olarak toplanıyor. Poligon birden fazla pafta üzerinde yayılıyorsa artık hepsi kaydediliyor" },
      { type: "feat", text: "Çizgi modunda da çizginin tüm vertex'lerinin paftaları toplanıyor — uzun çizgiler birden fazla paftayı kesiyorsa hepsi alınır" },
      { type: "feat", text: "LocationPickerResult'a 'paftalar: string[]' alanı eklendi (eski 'pafta' alanı geriye uyumluluk için korundu, ilk pafta oraya yazılıyor)" },
      { type: "feat", text: "Konum özet kartında (OperationLocationSection) pafta bilgisi artık görünür: '📐 Pafta: H21C02C' veya 'Paftalar (3): H21C02C, H21C02D, H21C03A'. Kullanıcı otomatik tespit edildiğini artık görüyor" },
      { type: "feat", text: "LocationPickerModal özet bölümünde de çoklu pafta gösterimi: tek pafta için 'Pafta: H21C02C', birden fazla için 'Paftalar (N): ...'" },
    ],
  },
  {
    version: "0.8.97",
    date: "2026-04-11",
    summary: "Takvim günü detayı sadeleştirildi + '+ Operasyon Ekle' belirginleşti + Saha Hazırlığı ekipman-only + harita zoom koruması",
    changes: [
      { type: "refactor", text: "Takvim gün detayı operasyon kartlarının altındaki hızlı durum değiştirme butonları (Talep/Saha/İşleme/Teslim) kaldırıldı. Durum değişimi artık operasyon modalında veya StatusBoard'da yapılıyor, takvim görünümü daha sade oldu" },
      { type: "feat", text: "'+ Operasyon Ekle' butonu belirginleştirildi: solid accent arka plan + beyaz yazı + shadow + active:scale-95 dokunma feedback'i + min-h 40px dokunma hedefi. Artık tıklanabilir hissi net" },
      { type: "refactor", text: "Saha Hazırlığı panelinde artık sadece operasyona atanmış ekipmanlar listeleniyor. Personel (assignedTeam) kalemleri kaldırıldı — ekipte kim olduğu operasyon modalında görünüyor, saha checklist'i sadece ekipman kontrolü" },
      { type: "fix", text: "Harita katman/filtre değiştirdiğinde otomatik zoom-out oluyordu. FitBounds artık yalnızca ilk mount'ta (ilk non-empty points geldiğinde) tetikleniyor, sonraki points değişikliklerinde haritanın kendi zoom/pan konumu korunuyor" },
      { type: "chore", text: "onStatusChange prop zinciri temizlendi: CalendarDayDetail → OperationCalendar → IhaDashboard. StatusBoard'daki drag-drop için hâlâ korunuyor" },
    ],
  },
  {
    version: "0.8.96",
    date: "2026-04-11",
    summary: "Operasyon modalı artık salt-okunur açılıyor — 'Düzenle' butonu ile edit moduna geçiliyor",
    changes: [
      { type: "feat", text: "Operasyon modalı varsayılan olarak salt-okunur (read-only) açılıyor. Mobilde operasyona tıkladığında artık otomatik klavye açılmıyor, yanlışlıkla alan değiştirme riski yok" },
      { type: "feat", text: "Modal alt çubuğuna '✎ Düzenle' butonu eklendi. Basılınca form düzenlenebilir hale geliyor, butonlar 'Vazgeç' ve 'Kaydet' olarak değişiyor. Vazgeç ile değişiklikler sıfırlanıp read-only moda dönülüyor" },
      { type: "refactor", text: "OperationForm'a readOnly prop'u eklendi. Tüm form içeriği <fieldset disabled={readOnly}> ile sarıldı — HTML'in yerleşik özelliği ile input/select/button/textarea tek hamlede disabled oluyor" },
      { type: "refactor", text: "OperationForm'un remount davranışı: isEditing değiştiğinde key prop'u ile component yeniden mount olur, kullanıcının yaptığı ama vazgeçtiği değişiklikler operation prop'undan yeniden hydrate olur" },
      { type: "docs", text: "OperationExtras (uçuş izni, kayıtlar, workflow, çıktılar, dosyalar) read-only davranışından etkilenmedi — oradaki butonlar kendi modalları açıyor, operasyon düzenlemesinden bağımsız" },
    ],
  },
  {
    version: "0.8.95",
    date: "2026-04-11",
    summary: "Mobil Footer çakışması + StatusBoard başlık tekrarı + DONE_LIMIT düzeltildi",
    changes: [
      { type: "fix", text: "v0.8.93'te yanlış teşhis yapılmıştı: mobil alt tab bar'ın altında görülen boşluk env(safe-area-inset-bottom) değil, Footer'ın kendisiydi. Marketing layout'un Footer'ı fixed tab bar ile çakışıyordu" },
      { type: "fix", text: "Footer.tsx client component'e çevrildi (usePathname). '/' rotasında mobilde 'hidden md:block' ile gizleniyor — alt tab bar artık browser URL bar'ına yapışık. Masaüstünde Footer aynen kalıyor (alt tab bar md:hidden)" },
      { type: "fix", text: "StatusBoard mobilde sütun başlığı çift yazılıyordu: üstte segmented control (YAPILACAK/YAPILIYOR/YAPILDI) + altta StatusColumn kendi header'ı. Sütun header'ı 'hidden md:flex' ile mobilde gizlendi, masaüstünde 3 sütunlu grid'de aynen kaldı" },
      { type: "refactor", text: "DONE_LIMIT 5 → 15'e çıkarıldı. YAPILDI sütununda artık son 15 tamamlanan operasyon görünüyor, sonrasında 'Tümünü gör (N)' butonu Operasyonlar sekmesine yönlendiriyor" },
      { type: "docs", text: "Mobilde kullanıcı versiyona/changelog'a hamburger menüsündeki VersionBadge kartından erişir (MobileMenu.tsx zaten içeriyor). Diğer marketing sayfaları (/about, /projects, /design) Footer'ı her cihazda gösteriyor" },
    ],
  },
  {
    version: "0.8.94",
    date: "2026-04-11",
    summary: "Genel Bakış sekmesi mobil UI sadeleştirildi: header kısaldı, StatusBoard mobilde segmented control'e çevrildi, YAPILDI'da 'Tümünü gör' butonu eklendi",
    changes: [
      { type: "refactor", text: "IhaBirimiContainer header sadeleşti: 'Yenile' butonu kaldırıldı (pull-to-refresh veya F5 ile yenileme), başlık mobilde text-lg/masaüstünde text-2xl, container padding py-6 → py-4" },
      { type: "refactor", text: "IhaTabNav'daki mobil 'GENEL BAKIŞ' label bloğu kaldırıldı (alt tab bar zaten aktif sekmeyi gösteriyor)" },
      { type: "feat", text: "StatusBoard mobilde yeniden tasarlandı: üstte segmented control (YAPILACAK/YAPILIYOR/YAPILDI pill butonları), altında sadece aktif durumun kartları tam genişlikte. Kart başlıkları artık kesilmiyor. Masaüstünde 3 sütun grid aynen kaldı" },
      { type: "feat", text: "YAPILDI sütunundaki '+X daha...' pasif metni 'Tümünü gör (N)' butonuna dönüştü — tıklayınca Operasyonlar sekmesine geçiş yapıyor" },
    ],
  },
  {
    version: "0.8.93",
    date: "2026-04-11",
    summary: "Mobil alt tab bar ile browser URL bar arasındaki boşluk kaldırıldı",
    changes: [
      { type: "fix", text: "Mobil alt tab bar (IhaTabNav MobileBottomNav) butonlarının altında görülen boşluk kaldırıldı — env(safe-area-inset-bottom) inline padding silindi, butonlar browser URL bar'ına yapışık duruyor" },
    ],
  },
  {
    version: "0.8.92",
    date: "2026-04-11",
    summary: "Bursa ilçe + mahalle sınırları haritaya eklendi, konum otomatik tespiti lokal GeoJSON'a geçti (offline çalışır)",
    changes: [
      { type: "feat", text: "Bursa 17 ilçe sınırları haritada yeni katman olarak açıldı (varsayılan açık, zoom 8+, 10+ iken kalıcı etiket)" },
      { type: "feat", text: "Bursa 1074 mahalle sınırları haritada yeni katman olarak açıldı (varsayılan kapalı, zoom 13+, viewport culling zorunlu)" },
      { type: "feat", text: "LocationPicker: operasyon konumu seçerken ilçe ve mahalle artık lokal GeoJSON'dan anında bulunuyor — ağ bağlantısı olmadan da çalışır" },
      { type: "perf", text: "Nominatim artık sadece sokak adı için çağrılıyor — ilçe/mahalle için ağ gidiş-gelişi kaldırıldı (hız + offline dayanıklılık)" },
      { type: "feat", text: "Türkçe title-case yardımcısı: \"NİLÜFER\" → \"Nilüfer\", \"MUSTAFAKEMALPAŞA\" → \"Mustafakemalpaşa\" (src/lib/turkish.ts)" },
      { type: "feat", text: "Harita filtre panelinde iki yeni katman toggle'ı: 🏙️ İlçe Sınırları, 🏘️ Mahalle Sınırları (paftanın yanında)" },
      { type: "chore", text: "ILCE.json + Mahalle.json public/vector/administrative/ altına taşındı ve bursa-ilceler.geojson + bursa-mahalleler.geojson olarak yeniden adlandırıldı" },
      { type: "docs", text: "Bursa Büyükşehir Belediyesi'nden gelen resmi sınır dosyaları projeye dahil edildi (WGS84, MultiPolygon)" },
    ],
  },
  {
    version: "0.8.91",
    date: "2026-04-11",
    summary: "Faz 7 (Auth+Roller+KVKK) planlandı, Vercel paralel deploy kararı alındı, ertelemesi MEMORY.md'ye kaydedildi",
    changes: [
      { type: "docs", text: "Faz 7 mimarisi kesinleşti: Auth + Roller (admin/pilot/izleyici) + KVKK. 8 alt faz (7A-7H) v0.8.91 → v0.9.0 arası" },
      { type: "docs", text: "Deploy stratejisi: GitHub Pages static export middleware/BFF desteklemiyor → Vercel paralel deploy seçildi (Yol C)" },
      { type: "docs", text: "Paralel deploy: next.config.ts dinamik olacak — GITHUB_ACTIONS env var ile GitHub Pages'te static export + basePath, Vercel'de standart SSR. Tek kod tabanı, iki deploy" },
      { type: "docs", text: "MEMORY.md'ye detaylı Faz 7 notu eklendi — alt fazlar, versiyon planı, kullanıcı tarafı Vercel kurulum adımları, neden Vercel seçildiği. Geri dönüldüğünde sıfırdan anlamaya gerek kalmayacak" },
      { type: "docs", text: "Faz 7 kullanıcı Vercel kurulumunu yapana kadar beklemede. Alternatif yollar (Edge Functions, tamamen ertele) değerlendirildi ve elendi" },
    ],
  },
  {
    version: "0.8.90",
    date: "2026-04-11",
    summary: "CLAUDE.md §3 dosya kuralları gerçekçi limitlere güncellendi (Seçenek C)",
    changes: [
      { type: "docs", text: "Eski kural (50 satır JSX) sistematik olarak ihlal ediliyordu — 10 dosya 327-415 satır arası. Kural yanlıştı, pratikte uygulanamıyordu" },
      { type: "docs", text: "Yeni limitler: Dosya max 400 satır (ESLint sektör standardı), top-level component max 150 satır JSX, sub-component limit yok, Hook max 50, Utility max 30" },
      { type: "docs", text: "Yeni ruh maddesi: 'Sayı bir rehber, mutlak değil. Yapısal bölme, yapay bölmeden iyidir' — sınırda olan dosyalar 'şüpheli' olarak değerlendirilir, hemen bölünmez" },
      { type: "docs", text: "CLAUDE.md §1 'Temel Felsefe' ilgili madde de güncellendi (50 satır → 400 satır/150 satır)" },
      { type: "docs", text: "Etki: Faz 4 (component refactor) kapsamı daralıyor — eski plan 10 dosyaydı, yeni kurallarla sadece 2-3 dosya (OperationCalendar 415, MapTab 414, WeeklyCalendar 402) gerçekten şüpheli" },
    ],
  },
  {
    version: "0.8.89",
    date: "2026-04-11",
    summary: "Faz 5 (hafif) + Faz 6 — Audit kapsamı ve burst deduplication cache",
    changes: [
      { type: "fix", text: "toggleVehicleEventComplete'e audit log çağrısı eklendi — 'tamamlandı/geri alındı' olarak iha_audit_log'a düşüyor (önceden sessizdi)" },
      { type: "perf", text: "Zustand store: _lastReload timestamp cache eklendi. reloadTable 1 saniye içinde aynı tablo için ikinci kez çağrılırsa atlıyor" },
      { type: "perf", text: "Sorunun kaynağı: mutation sonrası manuel reloadTable + Supabase realtime event aynı tabloyu 100-300ms içinde iki kere tetikliyordu → double fetch + UI flicker" },
      { type: "perf", text: "Sonuç: network tasarrufu + UI daha stabil + realtime cross-client sync hâlâ çalışıyor (1 saniye sonra)" },
      { type: "docs", text: "Faz 5 asıl iş (ihaStorage.ts 988 satırı 13 kategoriye bölme) Faz 4 component refactor dalgasıyla birleştirilmek üzere erteleniyor — atomic değişiklik kapsamı büyük, veri güvenliği riski orta, ayrı plan gerekli" },
    ],
  },
  {
    version: "0.8.88",
    date: "2026-04-11",
    summary: "Faz 3 — Hardcoded renkler feedback token'larına çevrildi (teknik borç ödeme)",
    changes: [
      { type: "refactor", text: "FormField merkezi: required '*' ve error mesajı artık text-[var(--feedback-error)] kullanıyor. Tüm formlarda tek noktadan tutarlı" },
      { type: "refactor", text: "FormCheckbox: error mesajı text-[var(--feedback-error)]" },
      { type: "refactor", text: "9 dosyada text-red-500 → text-[var(--feedback-error)] (QuickCreate/Permission/EquipmentCheckout/OperationForm/Modal/Deliverables/LocationPicker/StorageFolderList)" },
      { type: "refactor", text: "19 dosyada text-red-400 → text-[var(--feedback-error)] (Operation/Personnel/Location/ExcelImport 4 step/Weekly/Monthly Calendar/Info/Audit/Maintenance/Attachment/PasswordGate ve 8 tanesi daha)" },
      { type: "refactor", text: "text-green-400/500 → text-[var(--feedback-success)] (AuditLogList, Step3Preview, Step4Loading)" },
      { type: "refactor", text: "text-yellow-400/500 → text-[var(--feedback-warning)] (Step3Preview, Step4Loading, AuditLogList, PermissionCard, FlightPermissionsTab)" },
      { type: "refactor", text: "WeeklyCalendar şimdiki saat çizgisi bg-red-500 → bg-[var(--feedback-error)]" },
      { type: "docs", text: "Dışarıda bırakılan (bilinçli): PermissionBadge ve opacity'li durum badge'leri (bg-*/10 text-*) — CSS var ile Tailwind opacity syntax'ı kolayca çevrilmiyor, özel tasarım olarak korunuyor" },
    ],
  },
  {
    version: "0.8.87",
    date: "2026-04-11",
    summary: "Faz 2 tamamlandı — 5 form daha FormInput/FormSelect/FormTextarea'ya migrate edildi",
    changes: [
      { type: "refactor", text: "PersonnelForm migrate: Ad/TC/Doğum/Meslek/Telefon/E-posta/Adres/Durum/İzin/Lisans tüm alanlar FormInput/FormSelect/FormTextarea/FormCheckbox'a çevrildi" },
      { type: "refactor", text: "EquipmentForm migrate: 20+ field tamamen component'e çevrildi. Banner körlüğü olan 'ring-2 ring-red-500' Ek Ekipman Bilgileri çerçevesi temizlendi" },
      { type: "refactor", text: "PermissionForm migrate: HSD/Durum/Tarih/Yükseklik/Bölge Tipi/Koordinasyon/Koşullar/Notlar form component'e çevrildi. İki banner körlüğü temizliği: Bölge Tipi kırmızı çerçeve + 'Başvuru Bilgileri (YENİ)' kırmızı banner kaldırıldı" },
      { type: "refactor", text: "FlightLogForm migrate: 4 katlanabilir bölüm + Ek Parametreler + Konum + Özel Alanlar tüm alanlar FormInput/FormSelect/FormTextarea'ya. Ring-2 red banner temizlendi" },
      { type: "refactor", text: "QuickCreateForm migrate: LocationField ilçe seçici FormSelect'e, NameTimeField 3 input FormInput'a çevrildi. Kullanılmayan inputClass import'u silindi" },
      { type: "docs", text: "Faz 2 özeti: toplam 8 form migrate edildi. Desen uyumu tam, teknik borç ödendi. OperationForm 670+ satır Faz 4 component refactor'ında doğal olarak ele alınacak" },
    ],
  },
  {
    version: "0.8.86",
    date: "2026-04-11",
    summary: "Düzeltme: Haritadan konum seçerken ilçe/mahalle karışıklığı",
    changes: [
      { type: "fix", text: "parseNominatim ilçe öncelik sırası değişti: 'city_district' (büyükşehir ilçesi) → 'county' → 'municipality' → 'town'. Eskiden 'county' önceyken bazı noktalarda ilçe yerine il adı atanıyordu" },
      { type: "fix", text: "parseNominatim mahalle öncelik sırası değişti: 'neighbourhood' → 'quarter' → 'suburb'. Eskiden 'suburb' önceyken Nominatim bazı yerlerde suburb alanına ilçe adı yazıyordu (örn. 'Osmangazi' mahalle olarak görünüyordu)" },
      { type: "fix", text: "Temizlik 1: Nominatim mahalle ile ilçeyi birebir duplicate ederse (ikisi de 'Osmangazi' gibi), mahalle alanı temizleniyor" },
      { type: "fix", text: "Temizlik 2: Yeni helper 'isIlceName()' — mahalle alanında bir Bursa ilçe adı varsa (BURSA_ILCELER listesinde), mahalle silinip sadece ilçeye atanıyor" },
      { type: "fix", text: "normalizeIlce genişletildi: 'Osmangazi Belediyesi' → 'Osmangazi', 'Osmangazi İlçesi' → 'Osmangazi', 'Bursa Metropolitan' → 'Bursa' ekleri otomatik temizleniyor" },
    ],
  },
  {
    version: "0.8.85",
    date: "2026-04-11",
    summary: "Faz 2 — Form component'leri (desen uyumu + tekrar kullanım)",
    changes: [
      { type: "feat", text: "src/components/ui/formStyles.ts eklendi — inputClass/selectClass/textareaClass ui atom seviyesine taşındı (shared/styles.ts buradan re-export ediyor, 24 mevcut import bozulmadı)" },
      { type: "feat", text: "FormInput eklendi — label + htmlFor + aria-invalid otomatik, FormField üzerine ince sarmalama" },
      { type: "feat", text: "FormSelect eklendi — native select, aynı pattern" },
      { type: "feat", text: "FormTextarea eklendi — default resize-none, rows prop desteği" },
      { type: "feat", text: "FormCheckbox eklendi — inline label + useId + 44px touch target" },
      { type: "refactor", text: "StorageForm migrate edildi: 6 raw <label>+<input> → FormInput/FormSelect/FormTextarea. Banner körlüğü olan 'ring-2 ring-red-500' kırmızı çerçeve kaldırıldı (Backend'de var UI'da yoktu rozeti artık kalıcı olmuştu)" },
      { type: "refactor", text: "SoftwareForm migrate edildi: tüm raw form alanları FormInput/FormSelect/FormTextarea'ya çevrildi, kırmızı banner temizlendi" },
      { type: "refactor", text: "EquipmentCheckout migrate edildi: zimmet form alanları FormInput/FormSelect ile yeniden yazıldı" },
      { type: "docs", text: "Büyük formlar (PersonnelForm, PermissionForm, FlightLogForm, EquipmentForm, QuickCreateForm) Faz 4 component refactor'ı sırasında doğal olarak migrate edilecek" },
    ],
  },
  {
    version: "0.8.84",
    date: "2026-04-11",
    summary: "Faz 1 — UX geri bildirim + erişilebilirlik temizliği",
    changes: [
      { type: "feat", text: "9 update fonksiyonuna toast feedback eklendi (updateEquipment/Software/Storage/Operation/FlightLog/FlightPermission/VehicleEvent/toggleVehicleEventComplete/removeDeliverable) — eskiden kullanıcı 'güncellendi mi?' diye düşünüyordu, artık anında toast görüyor" },
      { type: "feat", text: "Modal.tsx'e role='dialog' + aria-modal='true' + focus trap + önceki elemana focus geri verme eklendi — ekran okuyucu ve klavye erişilebilirliği kapandı" },
      { type: "feat", text: "MapTab input'una aria-label='Operasyon ara' eklendi, 11 buton type='button' ile sarmalandı (form submit davranışına karşı korunma)" },
      { type: "fix", text: "fetchFieldPrep + fetchFieldPrepBatch sessizce hata yutuyorlardı, şimdi logger.warn ile dev'de görünüyor (prod'da sessiz)" },
    ],
  },
  {
    version: "0.8.83",
    date: "2026-04-11",
    summary: "v0.8.82 geri alındı — docs iskeletleri henüz gereksizdi",
    changes: [
      { type: "chore", text: "docs/offline-first.md, docs/kvkk.md, docs/hata-yonetimi.md dosyaları silindi — içerik MEMORY.md ve CLAUDE.md §16 'Gelecek Planlar'da zaten vardı, bilgi tekrarı ve her oturumda token israfı oluşturuyordu" },
      { type: "chore", text: "CLAUDE.md §4.3 tablosu eski hâline döndürüldü (Tasarım Referans Dosyaları başlığı + 5 satır)" },
    ],
  },
  {
    version: "0.8.81",
    date: "2026-04-11",
    summary: "TERIMLER.md denetimi — ölü kod, desen uyumu, erişilebilirlik, refaktör",
    changes: [
      { type: "chore", text: "Ölü kod silindi: TabHeader.tsx + OperationsKanban.tsx (import edilmiyordu)" },
      { type: "refactor", text: "FlightLogForm raw HTML × butonu Button variant=danger + IconTrash + aria-label'e çevrildi (desen uyumu)" },
      { type: "refactor", text: "FlightPermissionsTab accordion aksiyon butonları (Düzenle/Onayla/Sil) raw HTML'den Button component'e çevrildi + aria-label'lı" },
      { type: "refactor", text: "FlightPermissionsTab 'ring-2 ring-red-500' kırmızı çerçeveli 'Başvuru Bilgileri (YENİ)' etiketi kaldırıldı (banner körlüğü)" },
      { type: "refactor", text: "OperationForm LocationSection ayrı component'e çıkarıldı (OperationLocationSection.tsx) — 110 satır azaldı" },
      { type: "feat", text: "FormField utility component (src/components/ui/FormField.tsx) — useId + htmlFor + aria-invalid otomatik bağlama (gelecek form migration'ları için)" },
      { type: "feat", text: "formatAreaRaw + areaUnitLabel helper'ları (locationHelpers) — 3 yerdeki iç içe ternary temizlendi (OperationForm, QuickCreateForm, MapTab)" },
      { type: "feat", text: "Icon-only butonlara aria-label + type='button' eklendi (OperationDeliverables, InfoEntryModal, OperationsTab pagination, StatusBoard menu, OperationModal flight delete)" },
      { type: "docs", text: "TERIMLER.md sezgisel değerlendirme raporu uygulandı — desen uyumu, tutarlılık, erişilebilirlik iyileştirmeleri" },
    ],
  },
  {
    version: "0.8.80",
    date: "2026-04-11",
    summary: "Dinamik izin eşleşmesi + KML export + harita renk kodu + rapor Excel export",
    changes: [
      { type: "feat", text: "Dinamik uçuş izni eşleşmesi: operasyon konumu onaylı bir izin poligonu/dairesi içindeyse otomatik yeşil rozet. İzin sonradan oluştursa bile render-time'da güncellenir (DB değişikliği yok)" },
      { type: "feat", text: "İzin rozeti sadece İHA operasyonlarında gösterilir — LiDAR el/araç gibi uçuş gerektirmeyen tipler sade kalır" },
      { type: "feat", text: "PermissionBadge component: 🟢 onaylı · 🟡 süresi dolmuş · 🔴 izinsiz · (manuel/otomatik etiketi)" },
      { type: "feat", text: "findMatchingPermission() helper — point-in-polygon + haversine circle. op.permissionId manuel override olarak kalır" },
      { type: "feat", text: "KML export: OperationModal alt çubukta '📥 KML' butonu. Point/Polygon/LineString desteklenir, Google Earth'te açılır" },
      { type: "feat", text: "Custom KML writer (kmlWriter.ts) — yeni bağımlılık yok, XML escape güvenli" },
      { type: "feat", text: "Harita durum renk kodu (B6): operasyon poligon/çizgileri StatusBoard renkleriyle (turuncu/mavi/yeşil)" },
      { type: "feat", text: "ReportsTab 'Durum Grupları' kartı: Yapılacak/Yapılıyor/Yapıldı 3 sütun, her sütunda operasyon listesi (ilk 10, kalan expandable)" },
      { type: "feat", text: "ReportsTab '📥 Excel İndir' butonu — 3 sayfalı workbook: Operasyonlar · Uçuş Kayıtları · Özet (KPI)" },
      { type: "feat", text: "exportReportToExcel() lazy import — xlsx sadece butona basılınca yüklenir" },
      { type: "feat", text: "A-fix: OperationForm 'Detay' butonu her zaman erişilebilir (önceden sadece ilçe varsa)" },
      { type: "feat", text: "A-fix: allIlces bilgisi QuickCreateForm + OperationForm özet kartlarında gösteriliyor ('Osmangazi + Nilüfer')" },
      { type: "refactor", text: "usePaftaData.pointInPolygon + locationHelpers.haversineDistance export edildi (permissionMatcher kullanır)" },
    ],
  },
  {
    version: "0.8.79",
    date: "2026-04-11",
    summary: "UX iyileştirme paketi: sade form, collapse, PermissionForm'a Konum Seçici, çoklu ilçe tespiti",
    changes: [
      { type: "feat", text: "A-1: QuickCreateForm'da ilçe dropdown'u gizlendi, sadece 'İlçeyi elle gir' link'i ile açılır. Haritadan seçim birincil yol" },
      { type: "feat", text: "A-2: OperationForm konum bölümü collapse edildi — özet kart her zaman, il/ilçe/mahalle/sokak inputları 'Detay' butonu arkasında" },
      { type: "feat", text: "A-3: PermissionForm'daki manuel enlem/boylam input'ları kaldırıldı, yerine Konum Seçici modal — poligon haritadan çizilir veya KML/KMZ ile içe aktarılır" },
      { type: "feat", text: "A-4: Nominatim loading göstergesine spinner ikonu eklendi (IconLoader animate-spin)" },
      { type: "feat", text: "A-5: Modal harita yüksekliği responsive — mobilde h-56, tablette h-72, masaüstünde h-96" },
      { type: "feat", text: "A-6: 'Son Nokta' ve 'Temizle' butonlarına ikon eklendi (↶ geri al / 🗑 temizle)" },
      { type: "feat", text: "A-7: Çoklu nokta reverse geocoding — poligon için 5 nokta (centroid + N/S/E/W), çizgi için 3 nokta (başlangıç+orta+bitiş). Sınır aşan poligonlarda birden fazla ilçe tespit edilir: 'Osmangazi + Nilüfer'" },
      { type: "feat", text: "reverseGeocodeMulti() fonksiyonu + allIlces[] sonucu, MultiGeocodeResult tipi" },
      { type: "feat", text: "samplePolygonForGeocoding() + sampleLineForGeocoding() — küçük şekiller için tek nokta, büyükler için akıllı örnekleme" },
      { type: "refactor", text: "PermissionForm MapPolygon önizlemesi korundu, sadece input akışı değişti" },
    ],
  },
  {
    version: "0.8.78",
    date: "2026-04-11",
    summary: "Çizgi modu + düzenleme + harita render düzeltmesi + rapor metrikleri",
    changes: [
      { type: "feat", text: "Konum Seçici'ye Çizgi (polyline) modu eklendi: çoklu segmentli çizgi çizme, haversine ile uzunluk hesabı (m/km)" },
      { type: "feat", text: "Çizim bittikten sonra 'Düzenle' butonu: köşe üstüne tıklayıp sil veya haritaya tıklayıp yeni köşe ekle" },
      { type: "fix", text: "MapTab haritasında operasyon poligonları ve çizgileri gösterilmiyordu — şimdi render ediliyor (yeşil alan / mavi çizgi), tıklayınca operasyon detay modalı açılır" },
      { type: "fix", text: "MapTab filtresi artık sadece lat/lng olanları değil, poligon veya çizgisi olan operasyonları da harita sayfasında gösterir" },
      { type: "fix", text: "İlçe otomatik doldurma: Nominatim cevabı BURSA_ILCELER listesine Türkçe karakter ve case-insensitive normalleştirilerek eşleştirilir (Nilüfer, Osmangazi vb. tam eşleşir)" },
      { type: "feat", text: "Nominatim parser: county/city_district/municipality/town/suburb/neighbourhood/quarter fallback zinciri genişletildi" },
      { type: "feat", text: "ReportsTab 'Konum & Ölçüm' yeni kartı: Toplam Alan (m²/hektar/km²), Toplam Mesafe (m/km), nokta/alan/çizgi operasyon sayıları" },
      { type: "feat", text: "OperationLocation'a lineCoordinates + lineLength alanları eklendi" },
      { type: "chore", text: "SQL migration: iha_operations.line_coordinates jsonb + line_length double precision (kullanıcı çalıştıracak)" },
    ],
  },
  {
    version: "0.8.77",
    date: "2026-04-11",
    summary: "Konum Seçici modal + KML/KMZ içe aktarma + Nominatim reverse geocoding",
    changes: [
      { type: "refactor", text: "Paftalar çoklu seçim UI'ı (QuickCreateForm + OperationForm) tamamen kaldırıldı — artık haritadan otomatik doldurulur" },
      { type: "feat", text: "Konum Seçici modal: haritadan nokta veya poligon (alan) seçimi, tek tıklama / çoklu köşe çizimi" },
      { type: "feat", text: "Poligon çizimi: custom (harici lib YOK) — tıkla ekle, son noktayı sil, kapat, temizle aksiyonları" },
      { type: "feat", text: "Otomatik alan hesabı (shoelace) + birim seçimi (m²/hektar/km²)" },
      { type: "feat", text: "KML/KMZ içe aktarma: @tmcw/togeojson + jszip lazy load, ilk Point/Polygon alınır" },
      { type: "feat", text: "Nominatim reverse geocoding (OSM): ilçe/mahalle/sokak/tam adres otomatik doldurulur (rate limit 1.1sn)" },
      { type: "feat", text: "Operasyon şemasına polygonCoordinates + sokak + displayAddress alanları eklendi" },
      { type: "feat", text: "Harita sekmesinde operasyon poligonları görünür hale getirildi (yeşil fill)" },
      { type: "refactor", text: "OperationForm inline MapPicker (showMap toggle) yerine Konum Seç butonu + modal" },
      { type: "chore", text: "Yeni bağımlılıklar: @tmcw/togeojson, jszip" },
      { type: "chore", text: "SQL migration: iha_operations.polygon_coordinates jsonb + sokak text + display_address text (kullanıcı çalıştıracak)" },
    ],
  },
  {
    version: "0.8.76",
    date: "2026-04-11",
    summary: "Öncelik alanı tamamen kaldırıldı",
    changes: [
      { type: "refactor", text: "Operasyonlardan 'Öncelik' alanı kaldırıldı — form, tablo, kart, harita popup, kanban, seed ve tip tanımlarından tamamen silindi" },
      { type: "refactor", text: "OperationForm grid 3 sütundan 2 sütuna düştü (Durum + Başlangıç)" },
      { type: "chore", text: "priorityColors token, --priority-* CSS değişkenleri ve ColorPalette Öncelik bölümü kaldırıldı" },
      { type: "chore", text: "DB tarafında iha_operations.priority kolonu kalıyor — okunmuyor/yazılmıyor, ileride elle drop edilebilir" },
    ],
  },
  {
    version: "0.8.75",
    date: "2026-04-10",
    summary: "Excel içe aktarma wizard + operasyon modal sabit alt butonlar",
    changes: [
      { type: "feat", text: "Excel içe aktarma sihirbazı: 4 adım (Dosya → Eşleştir → Önizle → Aktar)" },
      { type: "feat", text: "Excel parse: xlsx kütüphanesi lazy load, ISO/DD.MM.YYYY/Excel serial tarih desteği" },
      { type: "feat", text: "Otomatik sütun eşleştirme: başlık benzerliği ile 15+ sistem alanı bulur" },
      { type: "feat", text: "Özel alanlar (custom fields): eşleşmeyen sütunları jsonb olarak sakla" },
      { type: "feat", text: "Önizleme tablosu + hata detayları (title/ilce zorunlu, eksikse satır atlanır)" },
      { type: "feat", text: "Operasyon modalı: Kaydet/İptal/Sil butonları sticky alt çubukta sabit kaldı" },
      { type: "refactor", text: "OperationForm: butonlar kaldırıldı, form id ile dışarıdan requestSubmit() ile gönderilir" },
      { type: "refactor", text: "OperationExtras: Sil butonu kaldırıldı (artık modal alt çubuğunda)" },
      { type: "chore", text: "WingtraImportModal + wingtra-import.ts silindi (hardcoded 13 demo veri)" },
      { type: "docs", text: "MEMORY.md: Excel wizard stratejisi + silinen dosyalar kaydedildi" },
      { type: "chore", text: "SQL migration: iha_operations.custom_fields jsonb + GIN index (kullanıcı çalıştıracak)" },
    ],
  },
  {
    version: "0.8.74",
    date: "2026-04-10",
    summary: "StatusBoard renkleri + tam navbar + pafta filtresi + popup sadeleştirme",
    changes: [
      { type: "feat", text: "StatusBoard: Yapılacak turuncu / Yapılıyor mavi / Yapıldı yeşil (aynı opaklık)" },
      { type: "fix", text: "StatusBoard mobilde tam label görünür (Yap/Yap/Yap kısaltması kaldırıldı)" },
      { type: "refactor", text: "Alt navbar 'Daha' butonu kaldırıldı — 9 sekme yatay kaydırılabilir" },
      { type: "refactor", text: "Pafta katmanı LayersControl'dan çıkarıldı → Filtre paneline taşındı (her tıklamada kapanma sorunu çözüldü)" },
      { type: "feat", text: "Pafta rengi: uydu görünümünde sarı (#fbbf24), diğer modlarda mavi" },
      { type: "feat", text: "IhaMapBase baselayerchange event listener ile aktif katman takibi" },
      { type: "refactor", text: "MapTab operasyon popup sadeleştirildi — 'sonraki durum' butonu kaldırıldı, minimalist içerik" },
      { type: "fix", text: "MapTab marker click artık detail modal'ı direkt açar (tek dokunuş)" },
      { type: "chore", text: "no-scrollbar CSS utility eklendi (bottom nav yatay scroll)" },
    ],
  },
  {
    version: "0.8.73",
    date: "2026-04-10",
    summary: "Pafta performansı + mobil UX + logger + Button/Lucide yaygınlaştırma",
    changes: [
      { type: "perf", text: "PaftaLayer: viewport culling (2301 → ~20-100 görünür polygon), etiket eşiği 14 → 13" },
      { type: "fix", text: "Mobil: Harita popup z-index düzeltildi (1 → 30, bottom nav altında kalmıyor)" },
      { type: "fix", text: "Mobil: inputClass globale min-h-[44px] eklendi (WCAG dokunma hedefi)" },
      { type: "fix", text: "Mobil: WeeklyCalendar saat sütunu 3rem → 2.5rem sm:3rem (sıkışma giderildi)" },
      { type: "fix", text: "Pafta etiketi uzun adlarda truncate (max-width 120px + ellipsis)" },
      { type: "feat", text: "Logger servisi: dev-only console, production'da no-op" },
      { type: "refactor", text: "usePaftaData + ihaStore console.error → logger.error" },
      { type: "feat", text: "4 sekmede EmptyState: Personnel, Inventory, InfoBank, Reports" },
      { type: "refactor", text: "QuickCreateForm + InfoEntryModal + VehicleEventsPanel ham butonlar → Button" },
      { type: "refactor", text: "FlightPermissionsTab + OperationModal emoji → Lucide (Edit, Trash, Check, Plane, FileText, Package, Paperclip)" },
      { type: "refactor", text: "MapTab popup ikonları: 📏📅 → IconRuler + IconCalendar" },
      { type: "fix", text: "OperationForm pafta picker + PersonnelForm * işareti + min-h[44px]" },
    ],
  },
  {
    version: "0.8.72",
    date: "2026-04-10",
    summary: "UX tutarlılık paketi — Button refactor, EmptyState yayılımı, Lucide ikonlar, TERIMLER.md",
    changes: [
      { type: "feat", text: "TERIMLER.md: yazılım/UX sözlüğü (darboğaz, teknik borç, tutarlılık, 50+ terim)" },
      { type: "refactor", text: "QuickCreateForm: 4 native button → Button component (TeamField, Paftalar, FormActions)" },
      { type: "feat", text: "EmptyState 4 yeni sekmede: PersonnelTab, InventoryTab, InfoBankTab, ReportsTab" },
      { type: "refactor", text: "FlightPermissionsTab: ✏️ 🗑️ action emoji → IconEdit, IconTrash (Lucide)" },
      { type: "refactor", text: "OperationModal sekme ikonları: 📄 🛩️ ✓ 📦 📎 → Lucide ikonları" },
      { type: "feat", text: "icons.ts: Paperclip (IconFiles), Plane (IconPlane) eklendi" },
    ],
  },
  {
    version: "0.8.71",
    date: "2026-04-10",
    summary: "Pafta etiketleri, harita tıklama kaldırıldı, Yapıldı sıralama",
    changes: [
      { type: "feat", text: "Pafta etiketleri: zoom >= 14 iken her pafta üstünde adı kalıcı gösterilir" },
      { type: "feat", text: ".pafta-label CSS stili: şeffaf beyaz arkaplan + mavi kenar, mobil uyumlu" },
      { type: "refactor", text: "Harita tıklama ile yeni operasyon oluşturma kaldırıldı (UX kazası engellendi)" },
      { type: "refactor", text: "MapTab: ClickHandler, newOpCoords, QuickCreate modal, kullanılmayan importlar silindi" },
      { type: "feat", text: "StatusBoard Yapıldı sütunu: son tamamlananlar en üstte (updatedAt desc)" },
    ],
  },
  {
    version: "0.8.70",
    date: "2026-04-10",
    summary: "Durum sistemi sadeleştirildi — 3 grup: Yapılacak / Yapılıyor / Yapıldı",
    changes: [
      { type: "feat", text: "OperationStatusGroup tipi eklendi: yapilacak / yapiliyor / yapildi" },
      { type: "feat", text: "getStatusGroup() helper: 7 durum → 3 grup eşleşmesi" },
      { type: "refactor", text: "OperationsTab filtresi: 'Tüm Durumlar' dropdown → 4 buton (Tümü/Yapılacak/Yapılıyor/Yapıldı)" },
      { type: "refactor", text: "MapTab filtre modalı: 6 durum butonu → 3 grup butonu + Tümü" },
      { type: "chore", text: "Detay ekranları (modal, timeline) hala 7 durum gösterir — hassas bilgi korundu" },
    ],
  },
  {
    version: "0.8.69",
    date: "2026-04-10",
    summary: "Saha hazırlığı sadeleştirildi — sadece envanter ekipmanları",
    changes: [
      { type: "refactor", text: "Saha Hazırlığı: ekipman alt maddeleri (batarya, SD kart vb.) kaldırıldı" },
      { type: "refactor", text: "Sadece envanterde atanmış ekipmanlar ve ekip üyeleri listelenir" },
      { type: "chore", text: "EQUIPMENT_PREP_ITEMS sabiti, isSubItem alanı, detay varyasyonları silindi" },
    ],
  },
  {
    version: "0.8.68",
    date: "2026-04-10",
    summary: "UX Faz 3 tamamlandı — emoji → Lucide ikonları (nav + butonlar)",
    changes: [
      { type: "feat", text: "icons.ts genişletildi: 15+ yeni Lucide ikon eklendi (nav, durum, işlem)" },
      { type: "refactor", text: "Mobil bottom nav: emoji ikonlar (🏠 🗺️) → Lucide (LayoutDashboard, Map, ClipboardList...)" },
      { type: "refactor", text: "'Daha' butonu → MoreHorizontal Lucide ikonu" },
      { type: "refactor", text: "OperationsTab 'Excel' butonu → FileUp Lucide ikonu" },
      { type: "chore", text: "Durum ikonları (✅ ⏳ ❌) FlightPermissionsTab'da semantik nedenlerle emoji olarak bırakıldı" },
    ],
  },
  {
    version: "0.8.67",
    date: "2026-04-10",
    summary: "UX Faz 3 (3/3) — native buttonlar Button'a, form etiketleri, EmptyState",
    changes: [
      { type: "refactor", text: "FlightPermissionsTab: 7 native button → Button component (primary/outline varyantları)" },
      { type: "refactor", text: "FlightPermissionsTab: local EmptyState → paylaşılan EmptyState bileşeni" },
      { type: "refactor", text: "OperationsTab: 'Sonuç yok' div → EmptyState (ikon + açıklama + CTA)" },
      { type: "fix", text: "Form zorunlu alan işaretleri: * → <span className='text-red-400'>*</span> (OperationForm, EquipmentForm)" },
    ],
  },
  {
    version: "0.8.66",
    date: "2026-04-10",
    summary: "UX Faz 3 (2/3) — mobil bottom nav, pafta popup, operasyon sekmeli",
    changes: [
      { type: "feat", text: "Mobil bottom tab bar: 4 ana sekme (Genel Bakış, Harita, Operasyonlar, İzinler) + 'Daha' butonu" },
      { type: "feat", text: "Mobilde üst sekmeler gizlendi, aktif sekme başlık olarak gösterilir" },
      { type: "feat", text: "'Daha' butonu → bottom sheet ile diğer 5 sekme (Envanter, Personel, Bilgi, Rapor, Ayarlar)" },
      { type: "refactor", text: "Pafta tıklama: tam ekran modal yerine harita üstü küçük popup + 'Detayı Gör' butonu" },
      { type: "refactor", text: "OperationModal alt bölümler sekmeli yapıya çevrildi (Uçuş İzni, Kayıtlar, İş Akışı, Çıktılar, Dosyalar)" },
      { type: "feat", text: "Sekme ikonları ile görsel navigasyon kolaylaştı" },
    ],
  },
  {
    version: "0.8.65",
    date: "2026-04-10",
    summary: "UX Faz 3 (1/3) — pafta performans, tıklama akışı sadeleştirme, arama standardı",
    changes: [
      { type: "perf", text: "Pafta katmanı zoom < 11 iken gizlenir — mobil performans sıçradı (2301 poligon yerine 0)" },
      { type: "refactor", text: "Haritaya tıklayınca pending pin ara adımı kaldırıldı — direkt modal açılır (3 adım → 2 adım)" },
      { type: "refactor", text: "PendingPinMarker bileşeni ve ilgili importlar silindi" },
      { type: "fix", text: "Arama placeholder'ları standartlaştırıldı: her yerde '🔍 Ara...'" },
    ],
  },
  {
    version: "0.8.64",
    date: "2026-04-10",
    summary: "UX iyileştirmeleri Faz 1 — modal, harita, pafta, tutarlılık altyapısı",
    changes: [
      { type: "fix", text: "Modal mobilde tam genişlik (max-w-full sm:max-w-lg + mx-2)" },
      { type: "fix", text: "Harita pending pin popup butonları min-h-[44px] dokunma alanı" },
      { type: "fix", text: "Leaflet CSS: LayersControl tap hedefi 44px, zoom kontrolleri 36px" },
      { type: "fix", text: "Pafta renklendirme: dominant status yerine en son operasyon durumu" },
      { type: "fix", text: "Harita mobil yüksekliği h-[50vh] → daha az overflow" },
      { type: "feat", text: "styles.ts: modalHeaderClass, modalFooterClass, labelClass, searchInputClass sabitleri" },
      { type: "feat", text: "EmptyState: paylaşılan boş durum bileşeni (icon + title + description + CTA)" },
    ],
  },
  {
    version: "0.8.63",
    date: "2026-04-10",
    summary: "Pafta ↔ Operasyon entegrasyonu — otomatik tespit, formda seçim, tıklama + renklendirme",
    changes: [
      { type: "feat", text: "usePaftaData: tek fetch, cache'li hook — tüm bileşenler paylaşır" },
      { type: "feat", text: "Nokta-içinde-poligon algoritması: haritaya tıklayınca otomatik pafta tespiti" },
      { type: "feat", text: "Operation tipine paftalar: string[] alanı eklendi (çoklu pafta desteği)" },
      { type: "feat", text: "Supabase iha_operations.paftalar kolonu (fallback ile backwards compat)" },
      { type: "feat", text: "QuickCreateForm + OperationForm: Paftalar alanı, chip görünümü, autocomplete" },
      { type: "feat", text: "Harita tıklama → pending pin popup'unda 'Pafta: H21C02C' otomatik görünür" },
      { type: "feat", text: "PaftaLayer: paftaya tıkla → o paftadaki operasyonlar modal'da listelenir" },
      { type: "feat", text: "Operasyonu olan paftalar durum rengine göre (saha=yeşil, teslim=mavi vb.) boyanır" },
    ],
  },
  {
    version: "0.8.62",
    date: "2026-04-10",
    summary: "Harita kontrol çakışması düzeltildi — arama/filtre harita dışına çıkarıldı",
    changes: [
      { type: "fix", text: "Arama ve Filtre butonu Leaflet zoom ve katman ikonlarıyla çakışıyordu" },
      { type: "refactor", text: "Arama + Filtre bar'ı haritanın dışına, üstüne alındı — çakışma yok" },
      { type: "refactor", text: "Alt sayaç haritanın içinde sol altta kaldı (z-[400] ile Leaflet üstünde)" },
    ],
  },
  {
    version: "0.8.61",
    date: "2026-04-10",
    summary: "2 kritik harita bug'ı düzeltildi — pin takılı kalma + marker click çakışması",
    changes: [
      { type: "fix", text: "Popup eventHandlers hatası: pin onay balonu kapanınca pin kaldırılıyordu ama pin takılı kalıyordu — PendingPinMarker ref ile popup yönetiliyor" },
      { type: "fix", text: "Marker click: var olan operasyona tıklayınca yanlışlıkla yeni pin düşüyordu — L.DomEvent.stopPropagation eklendi" },
      { type: "refactor", text: "PendingPinMarker ayrı bileşen olarak çıkarıldı — popupclose event ile temiz state yönetimi" },
    ],
  },
  {
    version: "0.8.60",
    date: "2026-04-10",
    summary: "Harita ekranı sadeleştirildi + UX düzeltmesi",
    changes: [
      { type: "refactor", text: "Üstteki 4 satır filtre tek satıra indirildi: arama + [Filtre] butonu" },
      { type: "refactor", text: "Tip filtresi (7 ikon) tamamen kaldırıldı — yeterince kullanılmıyordu" },
      { type: "refactor", text: "Alttaki renkli legend kaldırıldı — ikonlar zaten renkli" },
      { type: "feat", text: "[Filtre] butonu → modal panel (Gösterilen + Durum), aktif filtre sayacı" },
      { type: "feat", text: "Harita alanı büyüdü: 45vh → 60vh (mobilde)" },
      { type: "refactor", text: "Popup içeriği sadeleştirildi — gereksiz alanlar kaldırıldı" },
      { type: "fix", text: "UX: haritaya tıklayınca direkt modal açılmıyor — önce pin düşer, popup'tan [Ekle] onayı ile modal açılır" },
    ],
  },
  {
    version: "0.8.59",
    date: "2026-04-10",
    summary: "Pafta katmanı görünmeme sorunu düzeltildi — 2 kritik hata",
    changes: [
      { type: "fix", text: "next.config.ts'e NEXT_PUBLIC_BASE_PATH eklendi — fetch artık /spherical prefix'ini kullanır (404 hatası çözüldü)" },
      { type: "fix", text: "PaftaLayer: null return yerine FeatureGroup ile sarıldı — overlay checkbox katmanlar menüsünde her zaman görünür" },
      { type: "fix", text: "Fetch hatası artık console'a yazılır (sessiz başarısızlık kaldırıldı)" },
    ],
  },
  {
    version: "0.8.58",
    date: "2026-04-10",
    summary: "Bursa paftaları haritaya eklendi — 2301 pafta, tam hassasiyet",
    changes: [
      { type: "feat", text: "public/vector/pafta_index/ klasörü: shp, kmz, dbf, DGN vb. dosyalar" },
      { type: "feat", text: "bursa-paftalar.geojson: 2301 pafta, TUREF TM30 → WGS84 dönüştürüldü" },
      { type: "feat", text: "PaftaLayer bileşeni: harita katmanlar menüsünden açılabilir (lazy load)" },
      { type: "feat", text: "Her paftanın üzerine gelince adı tooltip olarak görünür" },
      { type: "chore", text: "Koordinat hassasiyeti: 14 hane (0.1mm altı — gerekenin 100x üstünde)" },
    ],
  },
  {
    version: "0.8.57",
    date: "2026-04-09",
    summary: "Wingtra Excel içe aktarma — ilk 13 kayıt için import ekranı",
    changes: [
      { type: "feat", text: "WingtraImportModal: Operasyonlar sekmesine 📥 Excel butonu eklendi" },
      { type: "feat", text: "13 kayıt için önizleme tablosu, özet kartları, ilerleme çubuğu" },
      { type: "feat", text: "Operatör isimleri personel listesiyle otomatik eşleştirilir" },
      { type: "feat", text: "Mükerrer pafta koruması — mevcut kayıtlar atlanır" },
      { type: "feat", text: "GSD/Rüzgar/Yazılım bilgileri notlara yazılır" },
    ],
  },
  {
    version: "0.8.56",
    date: "2026-04-09",
    summary: "Operasyon bitiş saati + haftalık takvimde saat bazlı sürükleme",
    changes: [
      { type: "feat", text: "QuickCreateForm: bitiş saati alanı eklendi (varsayılan 08:00-09:00)" },
      { type: "feat", text: "Haftalık takvim: operasyonlar sürüklenince saat de güncelleniyor (30dk snap)" },
      { type: "feat", text: "Sürüklemede operasyon süresi korunuyor (ör: 2 saatlik operasyon 2 saat kalır)" },
    ],
  },
  {
    version: "0.8.55",
    date: "2026-04-09",
    summary: "Saha Hazırlığı paneli yenilendi — dinamik checklist, Supabase entegrasyonu, Sahaya Hazırız butonu",
    changes: [
      { type: "feat", text: "Panel her zaman görünür — gün seçilmese bile bugünü otomatik gösterir" },
      { type: "feat", text: "Operasyon yoksa panel tam genişlik alır (sol boş → sağa yasla)" },
      { type: "feat", text: "Ekipman kategorisine göre alt maddeler: drone → batarya/SD/pervane, GPS → pil/tripod, araç → yakıt/navigasyon" },
      { type: "feat", text: "Checklist Supabase'e taşındı (iha_field_prep tablosu) — cihaz bağımsız" },
      { type: "feat", text: "Tüm maddeler tamamlanınca 'Sahaya Hazırız' butonu aktif → durumu otomatik 'saha'ya çevirir" },
      { type: "fix", text: "localStorage fallback korundu — tablo yoksa sessizce localStorage kullanır" },
    ],
  },
  {
    version: "0.8.54",
    date: "2026-04-09",
    summary: "Operasyon paneli sadeleştirildi — 3 adım → 2 adım, mobil iyileştirmeler",
    changes: [
      { type: "refactor", text: "Operasyon tıkla → direkt düzenleme formu (detay görünümü kaldırıldı)" },
      { type: "refactor", text: "Form + alt bölümler (izin, kayıt, çıktı, checklist, ek) tek panelde birleştirildi" },
      { type: "fix", text: "Kırmızı 'Gizli Alanlar' debug bölümü kaldırıldı" },
      { type: "fix", text: "OperationForm iç scroll kaldırıldı — Modal scroll'u yönetiyor" },
      { type: "chore", text: "OperationTimeline ölü kod silindi (hiçbir yerde kullanılmıyordu)" },
      { type: "fix", text: "Mobil: 3 sütunlu gridler sm: breakpoint ile responsive yapıldı" },
      { type: "fix", text: "Mobil: ekip/ekipman butonları min-h-[44px] dokunma alanına yükseltildi" },
    ],
  },
  {
    version: "0.8.52",
    date: "2026-04-09",
    summary: "Mükerrer kayıt koruması — seed mekanizması güçlendirildi",
    changes: [
      { type: "fix", text: "Seed fonksiyonları: maybeSingle() → limit(1) ile mükerrer kayıt önleme" },
      { type: "fix", text: "Seed: deleted kayıtlar dahil kontrol — soft delete sonrası tekrar ekleme engellendi" },
      { type: "fix", text: "Wingtra Gen2 mükerrer 7 kayıt DB'den temizlendi" },
    ],
  },
  {
    version: "0.8.51",
    date: "2026-04-09",
    summary: "Veri güvenliği katmanı — soft delete, silme onayı, hardcode renk düzeltmesi, güvenlik güncellemeleri",
    changes: [
      { type: "feat", text: "ConfirmDialog: tüm silme işlemlerinde profesyonel onay modal'ı (12 silme noktası)" },
      { type: "feat", text: "Soft Delete: 13 tabloya deleted_at kolonu — silinen veriler geri getirilebilir" },
      { type: "refactor", text: "12 delete fonksiyonu .delete() → .update({ deleted_at }) olarak güncellendi" },
      { type: "refactor", text: "14 fetch fonksiyonuna .is('deleted_at', null) filtresi eklendi" },
      { type: "fix", text: "7 hardcode hex renk tokens.ts'e taşındı (CLAUDE.md §4.2.5 uyumu)" },
      { type: "fix", text: "mapColors genişletildi: permissionPending, permissionRejected, newMarker, contrastText" },
      { type: "chore", text: "npm audit fix: brace-expansion ve picomatch güvenlik açıkları kapatıldı" },
      { type: "fix", text: "Mevcut 3 browser confirm() dialog'u profesyonel ConfirmDialog'a geçirildi" },
    ],
  },
  {
    version: "0.8.50",
    date: "2026-04-09",
    summary: "Lucide Icons entegrasyonu + design token tamamlama",
    changes: [
      { type: "feat", text: "Lucide Icons entegrasyonu — merkezi ikon yönetimi (src/config/icons.ts)" },
      { type: "feat", text: "Priority token'ları eklendi (acil/yüksek/normal/düşük)" },
      { type: "feat", text: "Feedback token'ları eklendi (success/error/info/warning)" },
      { type: "refactor", text: "StatusBoard: emoji → Lucide ikonları" },
      { type: "refactor", text: "Button/Toast/Badge: hardcode Tailwind → design token'ları" },
      { type: "refactor", text: "Icons.tsx: SVG → Lucide re-export (GitHub hariç)" },
    ],
  },
  {
    version: "0.8.49",
    date: "2026-04-09",
    summary: "DB kaydetme fallback güçlendirildi — sub_types kolonu yoksa da çalışır",
    changes: [
      { type: "fix", text: "upsertOperation: sub_types kolonu henüz eklenmemişse fallback ile kaydetme devam eder" },
      { type: "fix", text: "4 kademeli fallback: tüm alanlar → sub_types → time → sadece temel alanlar" },
    ],
  },
  {
    version: "0.8.48",
    date: "2026-04-09",
    summary: "Saha Hazırlığı paneli — takvimde gün seçildiğinde ekipman/ekip checklist'i",
    changes: [
      { type: "feat", text: "FieldPrepPanel: takvimde gün seçilince sağ 2/3'te saha hazırlığı paneli açılır" },
      { type: "feat", text: "Envantere eklenen her ekipman operasyona atandığında otomatik listede görünür" },
      { type: "feat", text: "Operasyona atanmış ekip üyeleri kontrol listesinde gösterilir" },
      { type: "feat", text: "Checkbox'lar localStorage ile kalıcı — gün bazlı hazırlık takibi" },
      { type: "feat", text: "İlerleme çubuğu: kaç item tamamlandı göstergesi" },
      { type: "feat", text: "Masaüstünde 1/3 + 2/3 grid layout, mobilde alt alta" },
    ],
  },
  {
    version: "0.8.47",
    date: "2026-04-09",
    summary: "Takvim çizgileri belirginleştirildi — aylık ve haftalık görünüm",
    changes: [
      { type: "feat", text: "Yeni --border-strong CSS değişkeni eklendi (takvim grid çizgileri için)" },
      { type: "fix", text: "Aylık takvim: gün hücreleri ve başlık çizgileri daha belirgin" },
      { type: "fix", text: "Haftalık takvim: saat ızgara çizgileri, gün başlıkları ve dikey ayırıcılar belirginleştirildi" },
    ],
  },
  {
    version: "0.8.46",
    date: "2026-04-09",
    summary: "Operasyon tipi 2 aşamalı seçim — İHA/LİDAR ana kategori + çoklu alt kategori",
    changes: [
      { type: "feat", text: "Operasyon oluşturma: 2 büyük butonla İHA/LİDAR seçimi, ardından çoklu alt kategori (Ortofoto, Oblik, 360°, El Tarama, Araç Tarama)" },
      { type: "feat", text: "TypeSelector bileşeni oluşturuldu — QuickCreateForm ve OperationForm'da ortak kullanım" },
      { type: "feat", text: "subTypes alanı eklendi — operasyonda birden fazla iş tipi seçilebilir" },
      { type: "feat", text: "Geriye uyumluluk: eski tip değerleri (drone_fotogrametri vb.) otomatik dönüştürülür" },
      { type: "refactor", text: "Tüm gösterim bileşenleri formatOperationType() helper ile güncellendi" },
    ],
  },
  {
    version: "0.8.45",
    date: "2026-04-09",
    summary: "Design System referans altyapısı + Tasarım Rehberi sayfası",
    changes: [
      { type: "feat", text: "Design System: canlı style guide sayfası eklendi (/design)" },
      { type: "docs", text: "docs/design-system.md oluşturuldu — tek tasarım referans dokümanı" },
      { type: "feat", text: "Navigasyona Tasarım linki eklendi (header + hamburger menü)" },
      { type: "docs", text: "CLAUDE.md §4 genişletildi — tasarım koruma kuralları eklendi" },
    ],
  },
  {
    version: "0.8.44",
    date: "2026-04-09",
    summary: "Darboğaz temizliği — ölü kod silindi, memoization, seed optimizasyonu",
    changes: [
      { type: "chore", text: "Ölü kod silindi: StatCard, AlertsList, QuickFlightLog (320 satır)" },
      { type: "perf", text: "StatusBoard: useMemo ile operasyon filtreleme optimize edildi" },
      { type: "perf", text: "Seed sonrası sadece değişen tablolar yenileniyor (full fetchAll yerine)" },
    ],
  },
  {
    version: "0.8.43",
    date: "2026-04-08",
    summary: "StatusBoard mobil desteği + dashboard modal düzenleme/silme aktif",
    changes: [
      { type: "fix", text: "StatusBoard: Mobilde dokunmatik sürükle-bırak alternatifi — ⋮ menüsüyle hızlı durum değişikliği" },
      { type: "fix", text: "Dashboard: OperationModal'da düzenleme ve silme artık çalışıyor (boş callback düzeltildi)" },
      { type: "feat", text: "StatusBoard: Mobilde sütun isimleri kısaltılmış (Yap → Yapılacak)" },
      { type: "chore", text: "Kullanılmayan OPERATION_TYPE_LABELS import'u kaldırıldı" },
    ],
  },
  {
    version: "0.8.42",
    date: "2026-04-08",
    summary: "Genel Bakış: KPI kartları yerine Mini Kart Listesi (Yapılacak/Yapılıyor/Yapıldı)",
    changes: [
      { type: "feat", text: "StatusBoard: 3 sütunlu mini kart listesi — Yapılacak, Yapılıyor, Yapıldı" },
      { type: "feat", text: "Sürükle-bırak ile operasyon durumu değiştirme (sütunlar arası)" },
      { type: "feat", text: "Operasyon ismine tıklayınca detay modalı açılır" },
      { type: "feat", text: "Yapıldı sütununda iptal operasyonlar soluk + üstü çizili" },
      { type: "feat", text: "Yapıldı sütunu max 5 operasyon + fazlası için '+X daha...' notu" },
      { type: "refactor", text: "4 StatCard KPI kartı kaldırıldı — StatusBoard ile değiştirildi" },
    ],
  },
  {
    version: "0.8.41",
    date: "2026-04-08",
    summary: "Araç Takip yeniden tasarım — mükerrer tab kaldırıldı, araçlar direkt kartla görünür, hata toleransı artırıldı",
    changes: [
      { type: "refactor", text: "Bilgi Bankası: mükerrer 'Araç Bilgileri' tabı kaldırıldı — tüm araç işlemleri 'Araç Takip' altında" },
      { type: "feat", text: "Araç Takip: Mevcut araçlar direkt kart olarak görünür — dropdown kaldırıldı" },
      { type: "feat", text: "Araç kartlarında bekleyen/gecikmiş etkinlik sayısı, sonraki etkinlik tarihi gösterilir" },
      { type: "fix", text: "Araç etkinlik formunda araç seçimi zorunlu yapıldı — validasyon eklendi" },
      { type: "fix", text: "iha_vehicle_events tablosu yoksa anlaşılır hata mesajı gösterilir" },
      { type: "chore", text: "Supabase schema SQL'e iha_vehicle_events tablo tanımı eklendi" },
    ],
  },
  {
    version: "0.8.40",
    date: "2026-04-08",
    summary: "Kaydetme hatası düzeltmesi, haftalık takvim overlap fix, Bilgi Bankası tüm kategoriler tab",
    changes: [
      { type: "fix", text: "Operasyon kaydetme hatası düzeltildi — start_time/end_time Supabase uyumluluğu" },
      { type: "fix", text: "Haftalık takvimde operasyonların üst üste binme sorunu düzeltildi — overlap layout algoritması" },
      { type: "feat", text: "Bilgi Bankası: TÜM kategoriler ayrı tab olarak gösterilir (Hesaplar, Lisanslar, Ağ, Sigorta, Araçlar, Diğer, Araç Takip)" },
      { type: "fix", text: "Haftalık takvim saat gösterimi düzeltildi (hourToStr fonksiyonu)" },
    ],
  },
  {
    version: "0.8.39",
    date: "2026-04-08",
    summary: "Bilgi Bankası tab yapısı + Araç etkinlik form bug fix'leri",
    changes: [
      { type: "feat", text: "Bilgi Bankası tab yapısına çevrildi: Bilgi Kayıtları | Araç Takip (Envanter pattern)" },
      { type: "fix", text: "Araç etkinlik form validation: boş başlık/tarih toast ile uyarı veriyor" },
      { type: "fix", text: "Tarih hesaplama timezone sorunu düzeltildi (local timezone kullanılıyor)" },
      { type: "fix", text: "Varsayılan araç seçimi: form açılınca ilk araç otomatik seçili" },
    ],
  },
  {
    version: "0.8.38",
    date: "2026-04-08",
    summary: "Google Calendar tarzı haftalık görünüm + operasyona saat alanı",
    changes: [
      { type: "feat", text: "Operation'a startTime/endTime alanları eklendi (varsayılan 08:00)" },
      { type: "feat", text: "QuickCreateForm'a saat seçici eklendi" },
      { type: "feat", text: "Haftalık takvim tamamen yeniden yazıldı: saat ızgarasında operasyonlar pozisyonlanıyor" },
      { type: "feat", text: "Şu anki saat kırmızı çizgiyle gösteriliyor (Google Calendar tarzı)" },
      { type: "feat", text: "Haftalık takvimde sürükle-bırak ile tarih değiştirme" },
    ],
  },
  {
    version: "0.8.34",
    date: "2026-04-08",
    summary: "Build hatası düzeltildi (ringColor → CSS variable)",
    changes: [
      { type: "fix", text: "CalendarDayDetail ringColor build hatası düzeltildi — geçersiz CSS property yerine Tailwind CSS variable kullanıldı" },
    ],
  },
  {
    version: "0.8.33",
    date: "2026-04-08",
    summary: "Takvim 4 büyük geliştirme: tip renkleri, hızlı durum, saat bloğu, sürükle-bırak",
    changes: [
      { type: "feat", text: "Operasyon tipi renkleri: LiDAR=mavi, Drone=mor, Oblik=pembe, Panorama=turkuaz — her tip farklı renk" },
      { type: "feat", text: "Takvimden direkt durum değiştirme: gün detayında 4 durum butonu (Talep/Saha/İşleme/Teslim)" },
      { type: "feat", text: "Haftalık görünümde saat ızgarası: 07:00-18:00 dekoratif saat çizgileri, üstte tüm gün etkinlikleri" },
      { type: "feat", text: "Sürükle-bırak: aylık takvimde operasyonları bir günden diğerine sürükleyip tarih değiştirme" },
      { type: "feat", text: "Takvim legend'ında tip renkleri tüm 5 operasyon tipi için gösteriliyor" },
    ],
  },
  {
    version: "0.8.32",
    date: "2026-04-08",
    summary: "Takvimden operasyon oluşturma tarih hatası düzeltildi",
    changes: [
      { type: "fix", text: "Takvimde güne tıklayıp operasyon oluşturulduğunda seçilen tarih kullanılıyor (eskiden her zaman bugünü alıyordu)" },
    ],
  },
  {
    version: "0.8.31",
    date: "2026-04-08",
    summary: "Bug fix: kullanılmayan prop temizliği",
    changes: [
      { type: "fix", text: "WeeklyCalendar'dan kullanılmayan 'operations' prop kaldırıldı" },
    ],
  },
  {
    version: "0.8.30",
    date: "2026-04-08",
    summary: "Araç takip sistemi — Bilgi Bankası + Takvim entegrasyonu",
    changes: [
      { type: "feat", text: "Araç etkinlik yönetimi: muayene, bakım, sigorta, lastik tarih takibi (VehicleEventsPanel)" },
      { type: "feat", text: "Bilgi Bankası'na 'Araç Bilgileri' kategorisi eklendi" },
      { type: "feat", text: "Araç etkinlikleri takvimde görünür — aylık ve haftalık modda" },
      { type: "feat", text: "Takvimde güne tıklanınca araç etkinlikleri ayrı bölümde listelenir" },
      { type: "feat", text: "Yaklaşan tarih uyarıları: 7 gün içinde sarı, geçmiş kırmızı" },
      { type: "feat", text: "Tamamlandı toggle: tek tıkla etkinlik durumu değiştir" },
      { type: "feat", text: "Envanter bağlantısı: etkinlikler araç ekipmanına equipment_id ile bağlı" },
    ],
  },
  {
    version: "0.8.29",
    date: "2026-04-08",
    summary: "Dashboard tam genişlik — masaüstünde sol-sağ boşluk kaldırıldı",
    changes: [
      { type: "feat", text: "Dashboard Container full genişliğe geçirildi — ekranın tamamını kullanır" },
    ],
  },
  {
    version: "0.8.28",
    date: "2026-04-08",
    summary: "Takvime haftalık görünüm eklendi + aylık takvim görsel iyileştirmesi",
    changes: [
      { type: "feat", text: "Haftalık takvim modu: Google Calendar tarzı 7 günlük görünüm, operasyon kartları, gün başlıkları" },
      { type: "feat", text: "Aylık/Haftalık geçiş toggle: header'da pill-style mod seçici" },
      { type: "feat", text: "Aylık takvimde gün numaraları büyütüldü, operasyonlu günler bold + renkli" },
      { type: "feat", text: "Operasyon sayısı badge: durum renginde yuvarlak sayı göstergesi" },
      { type: "feat", text: "Bugün göstergesi: accent renkli yuvarlak arka plan" },
      { type: "feat", text: "Operasyonlu günlerde renkli sol border (baskın durum rengi)" },
      { type: "refactor", text: "Takvim modüler yapıya bölündü: calendarConstants, MonthlyCalendar, WeeklyCalendar, CalendarLegend, CalendarDayDetail" },
    ],
  },
  {
    version: "0.8.27",
    date: "2026-04-08",
    summary: "Tüm backend alanları UI'a taşındı + form/UX iyileştirmeleri + hydration fix",
    changes: [
      { type: "feat", text: "Tüm Supabase alanları formlarda görünür: konum (mahalle/pafta/ada/parsel/alan), ekipman (durum/bakım/kalibrasyon/firmware), depolama (ip/path/tip), uçuş kaydı (tarama süresi/görüş), yazılım (yüklü bilgisayarlar)" },
      { type: "feat", text: "Bakım kayıtları UI (MaintenanceList) — ekipman detayında CRUD" },
      { type: "feat", text: "Dosya ekleri UI (AttachmentList) — operasyon + ekipman modalında yükleme/silme" },
      { type: "feat", text: "İşlem geçmişi UI (AuditLogList) — ayarlar sekmesinde audit log görüntüleme" },
      { type: "feat", text: "Uçuş izni: poligon/daire bölge tipi seçimi + daire merkez/yarıçap alanları" },
      { type: "feat", text: "Personel: profil fotoğrafı yükleme, pilot lisans belgesi yükleme" },
      { type: "feat", text: "Personel ayrı sekme oldu (8 sekme yapısı)" },
      { type: "feat", text: "Bilgi Bankası sekme + CRUD (hesap/lisans/ağ/sigorta)" },
      { type: "fix", text: "Tüm formlar <form> tag'ına dönüştürüldü — Enter tuşu çalışıyor" },
      { type: "fix", text: "Header hydration hatası düzeltildi (mounted guard)" },
      { type: "fix", text: "Personel ekleme hatası düzeltildi (role NOT NULL constraint)" },
      { type: "fix", text: "iha_team DB sütun eşleşmesi düzeltildi (specialties/certifications/skills)" },
      { type: "fix", text: "Store'da auditLog initialize'da yükleniyor" },
      { type: "refactor", text: "Dashboard sadeleştirildi: QuickAddForm ve ActiveOperations kaldırıldı" },
      { type: "chore", text: "Dead code temizliği: QuickAddForm, ActiveOperations, CheckoutList silindi" },
      { type: "chore", text: "Hata mesajları detaylandırıldı (onError gerçek Supabase hatası gösteriyor)" },
      { type: "docs", text: "CLAUDE.md: 8 sekme, 13 tablo, ekipman/operasyon detay yapısı güncellendi" },
    ],
  },
  {
    version: "0.8.26",
    date: "2026-04-07",
    summary: "CLAUDE.md tam güncelleme — sistem gerçek durumu kayıt altında",
    changes: [
      { type: "docs", text: "CLAUDE.md: Sistem Mimarisi bölümü tamamen yeniden yazıldı — gerçek durumu yansıtıyor" },
      { type: "docs", text: "CLAUDE.md: 6 sekme yapısı, Supabase entegrasyonu, operasyon detay modal yapısı belgelendi" },
      { type: "docs", text: "CLAUDE.md: §17 'Claude İçin Zorunlu Kurallar' bölümü eklendi — varsayım yapma, kontrol et, güncelle" },
      { type: "chore", text: "Eski/yanlış bilgiler temizlendi: 'localStorage', '9 tab', 'v0.7.x', 'SADECE İSKELET'" },
    ],
  },
  {
    version: "0.8.25",
    date: "2026-04-07",
    summary: "Profesyonel changelog sistemi + hamburger menü entegrasyonu",
    changes: [
      { type: "feat", text: "Changelog endüstri standardına yükseltildi: kategori rozetleri (feat/fix/refactor/perf/docs/chore)" },
      { type: "feat", text: "Changelog filtre sistemi: kategoriye göre değişiklik filtreleme" },
      { type: "feat", text: "Changelog istatistikleri: toplam sürüm, değişiklik sayısı, gün sayısı, kategori dağılımı çubuğu" },
      { type: "feat", text: "Changelog timeline görünümü: sol çizgi, genişletilebilir sürümler, güncel badge" },
      { type: "feat", text: "Hamburger menüye versiyon kartı: son güncelleme, sürüm sayısı, changelog'a geçiş" },
      { type: "refactor", text: "ChangelogEntry veri yapısı genişletildi: ChangeItem tipi, normalizeChange yardımcısı" },
    ],
  },
  {
    version: "0.8.24",
    date: "2026-04-07",
    changes: [
      "P1: Mobilde operasyon kartları (tablo yerine parmakla kullanılabilir kartlar)",
      "P1: Tek tıkla durum değiştirme (modal + kart üzerinde hızlı ilerleme butonları)",
      "P1: Operasyon arama çubuğu (başlık, talep eden, konum ile filtreleme)",
      "P1: Takvim mobil uyumluluk (büyük hücreler, gün tıklayınca detay paneli, noktalar)",
      "P2: Hızlı saha modu (9 alan → 3 alan: operasyon + pilot + GPS)",
      "P2: Operasyon formu sadeleştirme (14 → 6 temel alan + detaylar akordeonu)",
      "P2: Dashboard KPI iyileştirme (gecikmiş iş sayısı, haftalık özet)",
      "P3: Operasyon bitiş tarihi eklendi + takvimde tarih aralığı gösterimi",
      "P3: Tamamlanma yüzdesi otomatik hesaplama (duruma göre 0-100%)",
      "P3: Pagination (20 operasyon/sayfa, büyük veri setleri için)",
    ],
  },
  {
    version: "0.8.23",
    date: "2026-04-07",
    changes: [
      "Operasyonlar sekmesi sadece tablo görünümü (kanban/harita kaldırıldı)",
      "Harita ayrı sekme olarak geri eklendi (operasyonlar + izin bölgeleri + katman filtresi)",
      "Genel Bakış'a operasyon takvimi eklendi (aylık görünüm, duruma göre renkli)",
      "Sekme yapısı: Genel Bakış · Operasyonlar · Harita · Envanter · Raporlar · Ayarlar",
    ],
  },
  {
    version: "0.8.22",
    date: "2026-04-07",
    changes: [
      "Büyük yapı değişikliği: 9 sekme → 5 sekme",
      "Harita sekmesi Operasyonlar harita görünümüne birleştirildi (katman filtresi + legend + haritadan oluşturma)",
      "Uçuş İzinleri operasyon detayı içine taşındı — izin ekleme/düzenleme/silme inline",
      "Uçuş Defteri operasyon detayı içine taşındı — kayıt ekleme inline",
      "Personel + Depolama yeni Ayarlar sekmesinde birleştirildi",
      "Takvim görünümü kaldırıldı (kanban + tablo + harita yeterli)",
      "Konum formu 10 alandan 4'e sadeleştirildi",
      "6 eski sekme dosyası silindi (MapTab, PermissionsPanel, FlightLogTab, PersonnelTab, StorageTab, OperationsCalendar)",
    ],
  },
  {
    version: "0.8.21",
    date: "2026-04-07",
    changes: [
      "Gerçekçi demo veri: 7 operasyon (Bursa ilçeleri), 6 uçuş kaydı, gerçek ekipman/konum bilgileri",
      "Dashboard: 'Sahada' KPI kartı, son uçuş özeti, anlamlı depolama doluluk verileri",
      "Hızlı Uçuş Kaydı: sahadan tek butonla minimum alanla kayıt, GPS otomatik konum, operasyonla eşleşme",
      "Ekipman durumları güncellendi: Wingtra ve Stonex sahada kullanımda, uçuş saatleri eklendi",
    ],
  },
  {
    version: "0.8.20",
    date: "2026-04-07",
    changes: [
      "Ortak DataTable bileşeni: 4 tablo tek yapıya birleştirildi",
      "Ortak ViewToolbar bileşeni: 2 toolbar tek yapıya birleştirildi",
      "MapTab sadeleştirildi: 258 → 115 satır, tekrarlı detay kodu kaldırıldı",
      "OperationStatusBadge kaldırıldı, OPERATION_STATUS_VARIANTS merkezi yapıya taşındı",
      "8 gereksiz barrel index dosyası silindi",
    ],
  },
  {
    version: "0.8.19",
    date: "2026-04-07",
    changes: [
      "Genel Bakış tamamen yeniden tasarlandı — sadece önemli bilgiler",
      "Kaldırılan: Ekipman durumu, depolama, uçuş izinleri özeti, son uçuş kayıtları, 5 hızlı eylem butonu",
      "Uyarılar en üste taşındı, yoksa gizleniyor",
      "Aktif operasyonlar kartına 'Yeni Operasyon' butonu eklendi",
      "EquipmentStatusSummary ve StorageSummary bileşenleri silindi",
    ],
  },
  {
    version: "0.8.18",
    date: "2026-04-07",
    changes: [
      "Harita bileşenlerindeki hardcoded renkler mapColors token'ına taşındı",
      "Worktree artıkları temizlendi (silinen modüllerin dosyaları)",
    ],
  },
  {
    version: "0.8.17",
    date: "2026-04-07",
    changes: [
      "İHA modülü kapsamlı refactoring: ölü kod temizliği, performans, kod kalitesi",
      "N+1 sorgu problemi çözüldü (fetchOperations, fetchEquipment, fetchStorage)",
      "Tab değişiminde gereksiz tam reload kaldırıldı",
      "Maintenance sistemi ve offline queue ölü kodu temizlendi",
      "inputClass 13 dosyadan shared/styles.ts'e taşındı",
      "TabHeader paylaşılan bileşeni oluşturuldu",
      "Arama filtresi OperationsTab ve InventoryTab'da çalışır hale getirildi",
      "Form tarih validasyonları eklendi (OperationForm, PermissionForm, FlightLogForm)",
      "Hardcoded değerler config'e taşındı (Bursa, yıl listesi, ay isimleri, placeholder'lar)",
      "toast() helper fonksiyonu eklendi",
    ],
  },
  {
    version: "0.8.16",
    date: "2026-04-07",
    changes: [
      "Ana sayfa artık doğrudan İHA Birimi panelini gösteriyor",
      "İHA Birimi ayrı rotası (/iha-birimi) kaldırıldı — ana sayfa ile birleştirildi",
      "Navigasyon: İHA Birimi (ana sayfa), Projeler, Hakkımda",
      "DashboardGrid kaldırıldı, DashboardHeader ve DashboardCard korundu",
      "Lint düzeltmeleri: unused import/variable temizliği, React Hook pattern düzeltmeleri",
    ],
  },
  {
    version: "0.8.15",
    date: "2026-04-07",
    changes: [
      "Selim, Works, Blog, Kod Haritası modülleri tamamen kaldırıldı",
      "Blog ve Projeler sayfaları feature component yapısına refactor edildi",
      "Hakkımda sayfası feature component yapısına refactor edildi",
      "Navigasyon sadeleştirildi: Ana Sayfa, İHA Birimi, Projeler, Hakkımda",
      "gameColors ve codeMapColors token'ları kaldırıldı",
      "Work tipleri types/index.ts'den temizlendi",
      "Site açıklaması İHA Birimi odaklı güncellendi",
    ],
  },
  {
    version: "0.8.14",
    date: "2026-04-04",
    changes: [
      "Selim'in Dünyası: yerel geliştirme branch'ı canlıya entegre edildi",
      "Matematik quiz UI componentleri, sayfa layout'u ve ilerleme sistemi eklendi",
    ],
  },
  {
    version: "0.8.13",
    date: "2026-04-04",
    changes: [
      "İHA Modülü: Supabase (snake_case) ve Frontend (camelCase) veri eşleme sorunları giderildi",
      "Uçuş Kayıtları: Pilot ve ekipman isimlerinin veritabanına kaydedilmesi ve listede gösterilmesi sağlandı",
      "Konum Verileri: İl, ilçe ve koordinat bilgilerinin otomatik eşlenmesi tüm modüllerde aktif edildi",
    ],
  },
  {
    version: "0.8.11",
    date: "2026-04-01",
    changes: [
      "Envanter seed UUID hatası düzeltildi: seed ID'leri kaldırıldı, Supabase UUID üretir",
      "Name bazlı kontrol: aynı ekipman/yazılım tekrar eklenmez",
    ],
  },
  {
    version: "0.8.10",
    date: "2026-04-01",
    changes: [
      "Envanter seed güçlendirildi: her açılışta eksik varsayılan veriler Supabase'e otomatik eklenir",
    ],
  },
  {
    version: "0.8.9",
    date: "2026-04-01",
    changes: [
      "Envanter otomatik seed: Supabase'de donanım/yazılım boşsa varsayılan veriler otomatik yüklenir",
    ],
  },
  {
    version: "0.8.8",
    date: "2026-03-31",
    changes: [
      "Kod Haritası v2: Proje yöneticisi gözüyle tasarlandı — teknik bilgi gerektirmez",
      "Hiyerarşik katmanlı layout: üstten alta 6 katman — Sayfalar → Altyapı akışı",
      "Türkçe etiketler + emoji'ler: her modül anlaşılır isimle ve ikonla",
      "Bilgi paneli: node'a tıkla → ne olduğu, bağlantıları, açıklaması çıkar",
      "Grup kutuları: İHA, İş Takip, Selim modülleri renkli çerçevelerle ayrılır",
      "Katman başlıkları: 'Sayfalar — Kullanıcının gördüğü ekranlar' gibi açıklamalar",
    ],
  },
  {
    version: "0.8.5",
    date: "2026-03-29",
    changes: [
      "Selim sayfası eklendi: alt kategori yapısıyla eğitim platformu (/selim)",
      "Matematik bölümü: 20 soruluk interaktif quiz — kesirler, geometri, ondalık sayılar",
      "Minecraft temalı UI: XP bar, kalp sistemi, ipucu mekanizması, animasyonlar",
      "İleride Türkçe, Fen Bilimleri gibi yeni bölümler eklenebilir yapıda",
    ],
  },
  {
    version: "0.6.0",
    date: "2026-03-27",
    changes: [
      "İHA Birimi v2: Kapsamlı revize — 5 tab → 7 tab",
      "Uçuş Defteri (yeni): GPS/CORS, batarya, hava koşulları, özelleştirilebilir alanlar",
      "Raporlar (yeni): Aylık özet, ekipman kullanım, personel performans, talep analizi",
      "Operasyonlar: 4 görünüm (Kanban board, Tablo, Takvim, Harita)",
      "Operasyonlar: 5 tip + Konum detayı (İl/İlçe/Mahalle/Pafta/Ada/Parsel)",
      "Depolama: Klasör yapısı yönetimi",
      "Dashboard: Hızlı eylemler, son uçuş kayıtları",
      "Envanter: Zimmet takibi, bakım kayıtları, firmware/kalibrasyon",
      "Personel: Uzmanlık alanları, gerçekçi roller",
    ],
  },
  {
    version: "0.5.0",
    date: "2026-03-27",
    changes: [
      "CBS İHA Birimi Operasyon Yönetim Paneli eklendi (ilk sürüm)",
    ],
  },
  {
    version: "0.4.4",
    date: "2026-03-21",
    changes: [
      "Tek modal: iş oluşturma, düzenleme, ödeme, çalışan yönetimi tek yerde",
      "Form modal kaldırıldı — detay modal her şeyi yapıyor",
      "Yeni iş akışı: oluştur → aynı modal'da çalışan/ödeme ekle",
      "Konum düzenleme: harita açılıp kapanabiliyor",
      "Dinamik kaydet butonu: değişiklik varsa görünür",
    ],
  },
  {
    version: "0.4.2",
    date: "2026-03-21",
    changes: [
      "Çalışana ödeme takibi: her çalışana yapılan ödemeler ayrı kaydedilir",
      "Kalan alacak hesaplama: Toplam Alacak - Ödenen = Kalan otomatik güncellenir",
      "Pay % limiti: toplam pay %100'ü geçemez, form ve güncelleme engellenir",
      "İş silme onayı: 'Emin misiniz?' sorusu ile çift tıklama koruması",
      "Harcama/ödeme/çalışan silme onayı: tüm silme işlemlerinde onay adımı",
      "WorkWorkerPaymentList component: çalışan bazlı ödeme ekleme/silme UI",
      "Supabase: work_worker_payments tablosu gerekli",
    ],
  },
  {
    version: "0.4.0",
    date: "2026-03-20",
    changes: [
      "Adil pay dağılımı: Model B — harcamalar yüzdeye göre paylaşılır, harcayan geri alır",
      "Çalışan pay yüzdesi: her çalışana % pay atanır, toplam %100 uyarısı",
      "Ödeme geçmişi: her ödeme ayrı kayıt (tarih + tutar + not), toplam otomatik",
      "Net kâr hesaplama: toplam ücret - harcamalar = net kâr gösterimi",
      "Çalışan alacak hesaplama: (netKâr × pay%) + kendi harcamaları",
      "isAdmin kaldırıldı: şifre kapısından geçen her şeyi görür",
      "WorkPaymentList + WorkPaymentForm: ödeme ekleme/silme UI",
      "Supabase: work_payments tablosu, work_workers.share kolonu",
    ],
  },
  {
    version: "0.3.0",
    date: "2026-03-20",
    changes: [
      "İş takip sistemi genişletildi: finansal takip, çalışan yönetimi, harita",
      "Finansal takip: toplam ücret, alınan, kalan (otomatik hesaplama)",
      "Çalışan sistemi: her işe çalışan ekle, harcama girişi, alacak hesaplama",
      "Leaflet + OpenStreetMap harita entegrasyonu: pin ile konum seçimi",
      "Admin kontrolü: finansal bilgiler sadece şifre kapısından geçenlere görünür",
      "useAuth hook eklendi — admin durumu kontrolü",
      "useWorkDetail hook eklendi — çalışan + harcama yönetimi",
      "9 yeni component: finans, harita, çalışan, harcama UI'ları",
      "Supabase: work_workers ve work_expenses tabloları, works tablosu genişletildi",
    ],
  },
  {
    version: "0.2.13",
    date: "2026-03-20",
    changes: [
      "Supabase entegrasyonu: veriler artık bulutta, herkes aynı veriyi görüyor",
      "localStorage yerine Supabase PostgreSQL veritabanı kullanılıyor",
      "CRUD işlemleri (ekle/düzenle/sil) gerçek zamanlı veritabanına yazılıyor",
      "Loading spinner ve hata durumu eklendi",
      "Supabase client kütüphanesi (src/lib/supabase.ts) oluşturuldu",
    ],
  },
  {
    version: "0.2.12",
    date: "2026-03-20",
    changes: [
      "Düzenleme formu artık mevcut iş verilerini doğru yüklüyor (useEffect ile senkron)",
    ],
  },
  {
    version: "0.2.11",
    date: "2026-03-20",
    changes: [
      "İşlerim (/works) sayfası eklendi — ortak çalışma ve proje takip paneli",
      "Tablo + kart görünümü arası geçiş (toggle)",
      "Tam CRUD: iş ekle, düzenle, sil — sayfa içi formlar",
      "Durum filtreleme (Tamamlandı/Devam Ediyor/Beklemede) + müşteri filtresi",
      "Renkli durum badge'leri (yeşil/sarı/kırmızı)",
      "Detay modalı — işe tıklayınca bilgi açılır",
      "localStorage ile veri kalıcılığı, JSON seed data",
      "Modal UI componenti eklendi (src/components/ui/Modal.tsx)",
      "Navigasyona İşlerim linki eklendi",
    ],
  },
  {
    version: "0.2.10",
    date: "2026-03-20",
    changes: [
      "Şifre artık SHA-256 hash olarak saklanıyor, kaynak kodda düz metin yok",
    ],
  },
  {
    version: "0.2.9",
    date: "2026-03-20",
    changes: [
      "Şifre kapısı (PasswordGate) eklendi — basit client-side erişim kontrolü",
      "Auth config dosyası oluşturuldu (src/config/auth.ts)",
      "Şifre doğruysa 7 gün localStorage'da oturum hatırlanır",
      "Feature flag: auth aktif edildi",
    ],
  },
  {
    version: "0.2.8",
    date: "2026-03-20",
    changes: [
      "CLAUDE.md'ye design tokens zorunluluğu kuralı eklendi",
    ],
  },
  {
    version: "0.2.7",
    date: "2026-03-20",
    changes: [
      "Design tokens sistemi eklendi (src/config/tokens.ts)",
      "Renkler, tipografi, spacing, radius, gölge, animasyon, z-index, breakpoint sabitleri",
      "CSS değişkenleriyle senkron, TS tarafında erişilebilir",
    ],
  },
  {
    version: "0.2.6",
    date: "2026-03-20",
    changes: [
      "4 ESLint uyarısı düzeltildi (setState in useEffect anti-pattern)",
      "useMediaQuery: useSyncExternalStore ile yeniden yazıldı",
      "ThemeProvider & useTheme: resolvedTheme artık state yerine derive ediliyor",
      "Header: pathname değişikliğinde render-time state update pattern",
      "README.md Spherical'a özel içerikle güncellendi",
      "package.json versiyonu senkronize edildi",
      "Kullanılmayan platformNav kaldırıldı",
    ],
  },
  {
    version: "0.2.5",
    date: "2026-03-20",
    changes: [
      "CLAUDE.md: Git & Deploy akışı dokümante edildi",
      "Otomasyon akışı beyin dosyasına kaydedildi",
    ],
  },
  {
    version: "0.2.4",
    date: "2026-03-20",
    changes: [
      "Auto-merge workflow v3: merge + deploy ayrı adımlar",
      "Deploy workflow_dispatch ile tetikleniyor",
    ],
  },
  {
    version: "0.2.3",
    date: "2026-03-20",
    changes: [
      "Auto-merge workflow düzeltildi: PR yerine direkt merge + deploy",
      "Tek workflow ile merge ve deploy birleştirildi",
    ],
  },
  {
    version: "0.2.2",
    date: "2026-03-20",
    changes: [
      "GitHub Actions: claude/* branch otomatik PR + merge workflow eklendi",
      "Artık claude branch'e push = otomatik main'e merge",
    ],
  },
  {
    version: "0.2.1",
    date: "2026-03-20",
    changes: [
      "Semver versiyon yönetim sistemi eklendi",
      "Footer'da tıklanabilir versiyon badge'i",
      "Changelog modal: tüm versiyonları ve değişiklikleri gösterir",
      "BRAIN.md'ye versiyon kuralları eklendi",
    ],
  },
  {
    version: "0.2.0",
    date: "2026-03-20",
    changes: [
      "Chess.com tarzı dashboard ana sayfa iskeleti",
      "Koyu tema: yeşil/sarı accent renk paleti",
      "Header: ana sayfada gizli, diğerlerinde minimal",
      "Tam ekran hamburger mobil menü",
      "CSS değişken sistemi ile tema altyapısı",
      "Feature flags config eklendi",
      "Blog, Projeler, Hakkımda sayfaları iskelet olarak güncellendi",
      "SVG ikonlar ayrı modüle taşındı",
    ],
  },
  {
    version: "0.1.0",
    date: "2026-03-19",
    changes: [
      "Next.js 16 ile platform mimarisi kuruldu",
      "Temel sayfa yapısı: Ana Sayfa, Blog, Projeler, Hakkımda",
      "Tailwind CSS tema sistemi",
      "Dark/Light mode desteği",
      "Responsive header ve footer",
      "UI bileşenleri: Card, Badge, Button, Container",
    ],
  },
];
