import type {
  Equipment,
  Software,
  StorageUnit,
  TeamMember,
  Operation,
  FlightLog,
} from "@/types/iha";

// ============================================
// CBS İHA Birimi - Seed Data (v2)
// ============================================

export const SEED_EQUIPMENT: Equipment[] = [
  {
    id: "eq-001",
    name: "Xgrids L2 Pro",
    model: "L2 Pro",
    category: "tarayici",
    status: "musait",
    ownership: "sahip",
    condition: "iyi",
    notes: "Drone kiti ve araç kiti mevcut. El ile tarama + araç üstü tarama.",
    accessories: ["Drone Kiti", "Araç Kiti", "Şarj Ünitesi", "Taşıma Çantası"],
  },
  {
    id: "eq-002",
    name: "Stonex S990A",
    model: "S990A",
    category: "gps",
    status: "kullanımda",
    ownership: "sahip",
    condition: "iyi",
    notes: "Statik oturum ve RTK ölçüm. BUSAGA CORS ağı ile kullanılır.",
    accessories: ["Tripod", "Ölçüm Çubuğu", "Taşıma Çantası", "Radyo Modem"],
  },
  {
    id: "eq-003",
    name: "Wingtra Gen2",
    model: "Gen2",
    category: "drone",
    status: "kullanımda",
    ownership: "sahip",
    condition: "iyi",
    notes: "Sabit kanatlı VTOL drone. Geniş alan haritalama.",
    flightHours: 342,
    batteryCount: 2,
    totalBatteryCycles: 185,
    currentHolder: "Personel 2",
    accessories: ["Batarya x2", "Şarj Ünitesi", "Taşıma Kutusu", "Yedek Pervane"],
  },
  {
    id: "eq-004",
    name: "DJI Matrice 300 RTK",
    model: "Matrice 300 RTK",
    category: "drone",
    status: "musait",
    ownership: "sahip",
    condition: "iyi",
    notes: "Share 102S oblik kamera ile kullanılır. Oblik çekim ana platformu.",
    flightHours: 128,
    batteryCount: 4,
    totalBatteryCycles: 67,
    accessories: ["Share 102S Oblik Kamera", "Batarya x4", "Şarj Hub", "Taşıma Kutusu"],
  },
  {
    id: "eq-005",
    name: "DJI Matrice 4E",
    model: "Matrice 4E",
    category: "drone",
    status: "musait",
    ownership: "sahip",
    condition: "mukemmel",
    notes: "360° panorama çekimi ve genel amaçlı drone.",
    flightHours: 0,
    batteryCount: 2,
    totalBatteryCycles: 0,
    accessories: ["Batarya x2", "Şarj Ünitesi"],
  },
  {
    id: "eq-006",
    name: "DJI P1 Kamera",
    model: "Zenmuse P1",
    category: "kamera",
    status: "musait",
    ownership: "odunc",
    notes: "Harita şubeden ihtiyaç halinde alınır. Yüksek çözünürlüklü fotogrametri.",
  },
  {
    id: "eq-007",
    name: "DJI Phantom 4 RTK",
    model: "Phantom 4 RTK",
    category: "drone",
    status: "musait",
    ownership: "odunc",
    notes: "Harita şubeden ihtiyaç halinde alınır.",
    flightHours: 0,
    batteryCount: 0,
  },
  {
    id: "eq-008",
    name: "DJI Mini 4 Pro",
    model: "Mini 4 Pro",
    category: "drone",
    status: "musait",
    ownership: "odunc",
    notes: "Harita şubeden ihtiyaç halinde alınır. Keşif ve hızlı çekim.",
    flightHours: 0,
    batteryCount: 0,
  },
  {
    id: "eq-009",
    name: "Isuzu 4x4 Arazi Aracı",
    model: "Isuzu D-Max",
    category: "arac",
    status: "musait",
    ownership: "sahip",
    condition: "iyi",
    notes: "Saha operasyonları için arazi aracı. Xgrids araç kiti takılabilir.",
  },
  {
    id: "eq-010",
    name: "İş İstasyonu #1",
    model: "İş İstasyonu",
    category: "bilgisayar",
    status: "musait",
    ownership: "sahip",
    condition: "iyi",
  },
  {
    id: "eq-011",
    name: "İş İstasyonu #2",
    model: "İş İstasyonu",
    category: "bilgisayar",
    status: "musait",
    ownership: "sahip",
    condition: "iyi",
  },
  {
    id: "eq-012",
    name: "İş İstasyonu #3",
    model: "İş İstasyonu",
    category: "bilgisayar",
    status: "musait",
    ownership: "sahip",
    condition: "iyi",
  },
  {
    id: "eq-013",
    name: "İş İstasyonu #4",
    model: "İş İstasyonu",
    category: "bilgisayar",
    status: "musait",
    ownership: "sahip",
    condition: "iyi",
  },
];

export const SEED_SOFTWARE: Software[] = [
  { id: "sw-001", name: "Agisoft Metashape", licenseType: "perpetual", notes: "Fotogrametri ve nokta bulutu işleme." },
  { id: "sw-002", name: "Bentley iTwin Capture", licenseType: "subscription", notes: "Fotogrametri ve 3D modelleme." },
  { id: "sw-003", name: "Pix4D", licenseType: "subscription", notes: "Drone görüntü işleme ve haritalama." },
  { id: "sw-004", name: "DJI Terra", licenseType: "perpetual", notes: "DJI drone veri işleme." },
  { id: "sw-005", name: "QGIS", licenseType: "free", notes: "Açık kaynak CBS yazılımı." },
  { id: "sw-006", name: "ArcGIS", licenseType: "subscription", notes: "Esri CBS platformu." },
  { id: "sw-007", name: "NetCAD", licenseType: "perpetual", notes: "Harita ve CBS yazılımı." },
  { id: "sw-008", name: "AutoCAD", licenseType: "subscription", notes: "CAD çizim yazılımı." },
  { id: "sw-009", name: "Blender", licenseType: "free", notes: "3D modelleme ve görselleştirme." },
  { id: "sw-010", name: "MicroStation", licenseType: "subscription", notes: "Bentley CAD yazılımı." },
  { id: "sw-011", name: "StaticToRinex", licenseType: "free", notes: "GPS statik veri dönüşümü. PPK processing öncesi." },
  { id: "sw-012", name: "Lixel Studio", licenseType: "perpetual", notes: "Xgrids veri işleme, PPK processing, nokta bulutu üretimi." },
  { id: "sw-013", name: "Lixel Cyber Color", licenseType: "perpetual", notes: "Nokta bulutu renklendirme." },
  { id: "sw-014", name: "Cyclone", licenseType: "subscription", notes: "Leica nokta bulutu işleme ve kayıt." },
];

export const SEED_STORAGE: StorageUnit[] = [
  {
    id: "st-001",
    name: "ihaarsiv",
    type: "sunucu",
    totalCapacityTB: 10,
    usedCapacityTB: 6.2,
    notes: "İHA arşiv depolama sunucusu.",
    folders: [],
  },
  {
    id: "st-002",
    name: "cografidrone",
    type: "sunucu",
    totalCapacityTB: 60,
    usedCapacityTB: 43.7,
    notes: "Coğrafi drone veri depolama sunucusu. Ham ve işlenmiş veriler.",
    folders: [],
  },
];

export const SEED_TEAM: TeamMember[] = [
  { id: "tm-001", name: "Personel 1", profession: "Ekip Sorumlusu", status: "aktif" },
  { id: "tm-002", name: "Personel 2", profession: "Drone Pilotu", status: "aktif" },
  { id: "tm-003", name: "Personel 3", profession: "GPS Operatörü", status: "aktif" },
  { id: "tm-004", name: "Personel 4", profession: "Veri İşleme Uzmanı", status: "aktif" },
  { id: "tm-005", name: "Personel 5", profession: "LiDAR Operatörü", status: "aktif" },
  { id: "tm-006", name: "Personel 6", profession: "CBS Uzmanı", status: "aktif" },
  { id: "tm-007", name: "Personel 7", profession: "Teknisyen", status: "aktif" },
];

export const SEED_OPERATIONS: Operation[] = [
  {
    id: "op-001",
    title: "Osmangazi Kentsel Dönüşüm Haritalama",
    description: "Osmangazi ilçesi kentsel dönüşüm alanının ortofoto ve DEM üretimi",
    type: "drone_fotogrametri",
    requester: "İmar ve Şehircilik Dairesi",
    status: "teslim",
    priority: "yuksek",
    location: { il: "Bursa", ilce: "Osmangazi", mahalle: "Demirtaş", pafta: "h22d05d", lat: 40.2025, lng: 29.0175, alan: 850, alanBirimi: "hektar" },
    assignedTeam: ["tm-002", "tm-003"],
    assignedEquipment: ["eq-003", "eq-002"],
    deliverables: [
      { id: "del-001", type: "ortofoto", description: "5cm GSD ortofoto", deliveryMethod: "sunucu", filePath: "cografidrone/2025/osmangazi-donusum" },
      { id: "del-002", type: "dem", description: "DEM 1m çözünürlük", deliveryMethod: "sunucu" },
    ],
    flightLogIds: ["fl-001", "fl-002"],
    completionPercent: 100,
    startDate: "2025-09-10",
    endDate: "2025-10-05",
    dataStoragePath: "cografidrone/2025/osmangazi-donusum",
    createdAt: "2025-09-08T08:00:00Z",
    updatedAt: "2025-10-05T16:00:00Z",
  },
  {
    id: "op-002",
    title: "Nilüfer Belediyesi Yol Tarama",
    description: "Nilüfer ana cadde ve bulvarlarının araç üstü LiDAR taraması",
    type: "lidar_arac",
    requester: "Yol Bakım ve Altyapı Dairesi",
    status: "teslim",
    priority: "normal",
    location: { il: "Bursa", ilce: "Nilüfer", mahalle: "Beşevler", lat: 40.2115, lng: 28.9560, alan: 12, alanBirimi: "km2" },
    assignedTeam: ["tm-005", "tm-003", "tm-007"],
    assignedEquipment: ["eq-001", "eq-002", "eq-009"],
    deliverables: [
      { id: "del-003", type: "nokta_bulutu", description: "Yol nokta bulutu — COPC format", deliveryMethod: "sunucu" },
    ],
    flightLogIds: ["fl-003"],
    completionPercent: 100,
    startDate: "2025-11-15",
    endDate: "2025-12-20",
    dataStoragePath: "cografidrone/2025/nilufer-yol-tarama",
    createdAt: "2025-11-10T08:00:00Z",
    updatedAt: "2025-12-20T16:00:00Z",
  },
  {
    id: "op-003",
    title: "Mudanya Sahil Oblik Çekim",
    description: "Mudanya sahil şeridi 3D şehir modeli için oblik çekim",
    type: "oblik_cekim",
    requester: "Mudanya Belediyesi",
    status: "isleme",
    priority: "normal",
    location: { il: "Bursa", ilce: "Mudanya", mahalle: "Güzelyalı", lat: 40.3760, lng: 28.8830, alan: 450, alanBirimi: "hektar" },
    assignedTeam: ["tm-002", "tm-003"],
    assignedEquipment: ["eq-004", "eq-002"],
    deliverables: [],
    flightLogIds: ["fl-004", "fl-005"],
    completionPercent: 60,
    startDate: "2026-03-20",
    dataStoragePath: "cografidrone/2026/mudanya-oblik",
    createdAt: "2026-03-15T08:00:00Z",
    updatedAt: "2026-04-05T10:00:00Z",
  },
  {
    id: "op-004",
    title: "Yıldırım Cami Restorasyonu LiDAR",
    description: "Yıldırım Beyazıt Camii restorasyon öncesi iç-dış LiDAR tarama",
    type: "lidar_el",
    requester: "Kültür ve Turizm Dairesi",
    status: "kontrol",
    priority: "yuksek",
    location: { il: "Bursa", ilce: "Yıldırım", mahalle: "Yıldırım", lat: 40.1880, lng: 29.0645, alan: 3500, alanBirimi: "m2" },
    assignedTeam: ["tm-005", "tm-004"],
    assignedEquipment: ["eq-001"],
    deliverables: [
      { id: "del-004", type: "nokta_bulutu", description: "İç-dış birleşik nokta bulutu", deliveryMethod: "sunucu" },
      { id: "del-005", type: "rapor", description: "Tarama raporu", deliveryMethod: "eposta" },
    ],
    flightLogIds: [],
    completionPercent: 80,
    startDate: "2026-03-25",
    dataStoragePath: "cografidrone/2026/yildirim-cami-lidar",
    createdAt: "2026-03-20T08:00:00Z",
    updatedAt: "2026-04-06T14:00:00Z",
  },
  {
    id: "op-005",
    title: "İnegöl Sanayi Bölgesi Haritalama",
    description: "İnegöl OSB genişleme alanının fotogrametrik haritalanması",
    type: "drone_fotogrametri",
    requester: "İnegöl Belediyesi",
    status: "saha",
    priority: "acil",
    location: { il: "Bursa", ilce: "İnegöl", mahalle: "Organize Sanayi", lat: 40.0780, lng: 29.5120, alan: 1200, alanBirimi: "hektar" },
    assignedTeam: ["tm-002", "tm-003", "tm-007"],
    assignedEquipment: ["eq-003", "eq-002", "eq-009"],
    deliverables: [],
    flightLogIds: ["fl-006"],
    completionPercent: 30,
    startDate: "2026-04-05",
    dataStoragePath: "cografidrone/2026/inegol-osb",
    createdAt: "2026-04-01T08:00:00Z",
    updatedAt: "2026-04-07T09:00:00Z",
  },
  {
    id: "op-006",
    title: "Gemlik Liman 360° Panorama",
    description: "Gemlik limanı ve çevresinin 360° panoramik belgeleme",
    type: "panorama_360",
    requester: "Ulaşım Dairesi",
    status: "planlama",
    priority: "normal",
    location: { il: "Bursa", ilce: "Gemlik", mahalle: "Liman", lat: 40.4310, lng: 29.1575 },
    assignedTeam: ["tm-002"],
    assignedEquipment: ["eq-005"],
    deliverables: [],
    flightLogIds: [],
    completionPercent: 0,
    startDate: "2026-04-14",
    notes: "SHGM izni bekleniyor",
    createdAt: "2026-04-03T08:00:00Z",
    updatedAt: "2026-04-07T08:00:00Z",
  },
  {
    id: "op-007",
    title: "Karacabey Ovası Tarım Haritalama",
    description: "Karacabey ovasında tarımsal alan kullanım haritası üretimi",
    type: "drone_fotogrametri",
    requester: "Tarım ve Orman İl Müdürlüğü",
    status: "talep",
    priority: "dusuk",
    location: { il: "Bursa", ilce: "Karacabey", mahalle: "Bayramdere", lat: 40.2130, lng: 28.3640, alan: 5000, alanBirimi: "hektar" },
    assignedTeam: [],
    assignedEquipment: [],
    deliverables: [],
    flightLogIds: [],
    completionPercent: 0,
    createdAt: "2026-04-06T08:00:00Z",
    updatedAt: "2026-04-06T08:00:00Z",
  },
];

export const SEED_FLIGHT_LOGS: FlightLog[] = [
  {
    id: "fl-001",
    operationId: "op-001",
    type: "drone_fotogrametri",
    date: "2025-09-15",
    startTime: "08:30",
    endTime: "11:45",
    duration: 195,
    pilotId: "tm-002",
    pilotName: "Personel 2",
    equipmentId: "eq-003",
    equipmentName: "Wingtra Gen2",
    altitude: 120,
    gsd: 2.5,
    overlapForward: 80,
    overlapSide: 70,
    photoCount: 2450,
    gpsBaseStation: "Stonex S990A",
    staticDuration: 45,
    corsConnection: "BUSAGA",
    ppkStatus: "tamamlandi",
    weather: "Açık",
    windSpeed: 8,
    temperature: 24,
    location: { il: "Bursa", ilce: "Osmangazi", mahalle: "Demirtaş" },
    notes: "3 sorti yapıldı. İlk sorti rüzgar nedeniyle erken sonlandırıldı.",
    createdAt: "2025-09-15T12:00:00Z",
    updatedAt: "2025-09-15T12:00:00Z",
  },
  {
    id: "fl-002",
    operationId: "op-001",
    type: "drone_fotogrametri",
    date: "2025-09-18",
    startTime: "07:45",
    endTime: "10:30",
    duration: 165,
    pilotId: "tm-002",
    pilotName: "Personel 2",
    equipmentId: "eq-003",
    equipmentName: "Wingtra Gen2",
    altitude: 120,
    gsd: 2.5,
    overlapForward: 80,
    overlapSide: 70,
    photoCount: 1870,
    gpsBaseStation: "Stonex S990A",
    staticDuration: 40,
    corsConnection: "BUSAGA",
    ppkStatus: "tamamlandi",
    weather: "Parçalı bulutlu",
    windSpeed: 5,
    temperature: 22,
    location: { il: "Bursa", ilce: "Osmangazi", mahalle: "Demirtaş" },
    notes: "2 sorti ile tamamlandı.",
    createdAt: "2025-09-18T11:00:00Z",
    updatedAt: "2025-09-18T11:00:00Z",
  },
  {
    id: "fl-003",
    operationId: "op-002",
    type: "lidar_arac",
    date: "2025-11-20",
    startTime: "09:00",
    endTime: "16:30",
    duration: 450,
    pilotId: "tm-005",
    pilotName: "Personel 5",
    equipmentId: "eq-001",
    equipmentName: "Xgrids L2 Pro",
    gpsBaseStation: "Stonex S990A",
    staticDuration: 30,
    corsConnection: "BUSAGA",
    ppkStatus: "tamamlandi",
    weather: "Açık",
    windSpeed: 3,
    temperature: 12,
    location: { il: "Bursa", ilce: "Nilüfer", mahalle: "Beşevler" },
    notes: "Araç üstü tarama. 45km yol tarandı.",
    createdAt: "2025-11-20T17:00:00Z",
    updatedAt: "2025-11-20T17:00:00Z",
  },
  {
    id: "fl-004",
    operationId: "op-003",
    type: "oblik_cekim",
    date: "2026-03-25",
    startTime: "08:00",
    endTime: "12:15",
    duration: 255,
    pilotId: "tm-002",
    pilotName: "Personel 2",
    equipmentId: "eq-004",
    equipmentName: "DJI Matrice 300 RTK",
    altitude: 200,
    photoCount: 8500,
    gpsBaseStation: "Stonex S990A",
    staticDuration: 35,
    corsConnection: "BUSAGA",
    ppkStatus: "tamamlandi",
    weather: "Açık",
    windSpeed: 10,
    temperature: 16,
    location: { il: "Bursa", ilce: "Mudanya", mahalle: "Güzelyalı" },
    notes: "5 sorti. Share 102S oblik kamera ile çekim.",
    createdAt: "2026-03-25T13:00:00Z",
    updatedAt: "2026-03-25T13:00:00Z",
  },
  {
    id: "fl-005",
    operationId: "op-003",
    type: "oblik_cekim",
    date: "2026-03-28",
    startTime: "08:30",
    endTime: "11:00",
    duration: 150,
    pilotId: "tm-002",
    pilotName: "Personel 2",
    equipmentId: "eq-004",
    equipmentName: "DJI Matrice 300 RTK",
    altitude: 200,
    photoCount: 5200,
    gpsBaseStation: "Stonex S990A",
    staticDuration: 30,
    corsConnection: "BUSAGA",
    ppkStatus: "beklemede",
    weather: "Parçalı bulutlu",
    windSpeed: 12,
    temperature: 14,
    location: { il: "Bursa", ilce: "Mudanya", mahalle: "Güzelyalı" },
    notes: "3 sorti. Kıyı şeridi tamamlandı.",
    createdAt: "2026-03-28T12:00:00Z",
    updatedAt: "2026-03-28T12:00:00Z",
  },
  {
    id: "fl-006",
    operationId: "op-005",
    type: "drone_fotogrametri",
    date: "2026-04-06",
    startTime: "07:30",
    endTime: "13:00",
    duration: 330,
    pilotId: "tm-002",
    pilotName: "Personel 2",
    equipmentId: "eq-003",
    equipmentName: "Wingtra Gen2",
    altitude: 150,
    gsd: 3.0,
    overlapForward: 80,
    overlapSide: 65,
    photoCount: 3100,
    gpsBaseStation: "Stonex S990A",
    staticDuration: 50,
    corsConnection: "BUSAGA",
    ppkStatus: "beklemede",
    weather: "Açık",
    windSpeed: 6,
    temperature: 18,
    location: { il: "Bursa", ilce: "İnegöl", mahalle: "Organize Sanayi" },
    notes: "İlk gün çekimi. 4 sorti. Yarın devam edilecek.",
    createdAt: "2026-04-06T14:00:00Z",
    updatedAt: "2026-04-06T14:00:00Z",
  },
];
