import type {
  Equipment,
  Software,
  StorageUnit,
  TeamMember,
  Operation,
} from "@/types/iha";

// ============================================
// CBS İHA Birimi - Seed Data
// ============================================

export const SEED_EQUIPMENT: Equipment[] = [
  {
    id: "eq-001",
    name: "Xgrids L2 Pro",
    model: "L2 Pro",
    category: "tarayici",
    status: "musait",
    ownership: "sahip",
    notes: "Drone kiti ve araç kiti mevcut. El ile tarama + araç üstü tarama.",
    accessories: ["Drone Kiti", "Araç Kiti", "Şarj Ünitesi"],
  },
  {
    id: "eq-002",
    name: "Stonex S990A",
    model: "S990A",
    category: "gps",
    status: "musait",
    ownership: "sahip",
    notes: "Statik oturum ve RTK ölçüm için kullanılır.",
    accessories: ["Tripod", "Ölçüm Çubuğu", "Taşıma Çantası"],
  },
  {
    id: "eq-003",
    name: "Wingtra Gen2",
    model: "Gen2",
    category: "drone",
    status: "musait",
    ownership: "sahip",
    notes: "Sabit kanatlı VTOL drone. Geniş alan haritalama.",
    flightHours: 0,
    batteryCount: 2,
    accessories: ["Batarya x2", "Şarj Ünitesi", "Taşıma Kutusu"],
  },
  {
    id: "eq-004",
    name: "DJI Matrice 300 RTK",
    model: "Matrice 300 RTK",
    category: "drone",
    status: "musait",
    ownership: "sahip",
    notes: "Share 102S oblik kamera ile kullanılır.",
    flightHours: 0,
    batteryCount: 4,
    accessories: ["Share 102S Oblik Kamera", "Batarya x4", "Şarj Hub"],
  },
  {
    id: "eq-005",
    name: "DJI Matrice 4E",
    model: "Matrice 4E",
    category: "drone",
    status: "musait",
    ownership: "sahip",
    flightHours: 0,
    batteryCount: 2,
    accessories: ["Batarya x2", "Şarj Ünitesi"],
  },
  {
    id: "eq-006",
    name: "DJI P1 Kamera",
    model: "Zenmuse P1",
    category: "kamera",
    status: "musait",
    ownership: "odunc",
    notes: "Harita şubeden ihtiyaç halinde alınır.",
  },
  {
    id: "eq-007",
    name: "DJI Phantom 4 RTK",
    model: "Phantom 4 RTK",
    category: "drone",
    status: "musait",
    ownership: "odunc",
    notes: "Harita şubeden ihtiyaç halinde alınır.",
    flightHours: 0,
    batteryCount: 0,
  },
  {
    id: "eq-008",
    name: "DJI Mini 4 Pro",
    model: "Mini 4 Pro",
    category: "drone",
    status: "musait",
    ownership: "odunc",
    notes: "Harita şubeden ihtiyaç halinde alınır.",
    flightHours: 0,
    batteryCount: 0,
  },
  {
    id: "eq-009",
    name: "Isuzu 4x4 Arazi Aracı",
    model: "Isuzu D-Max",
    category: "arac",
    status: "musait",
    ownership: "sahip",
    notes: "Saha operasyonları için arazi aracı.",
  },
  {
    id: "eq-010",
    name: "İş İstasyonu #1",
    model: "İş İstasyonu",
    category: "bilgisayar",
    status: "musait",
    ownership: "sahip",
  },
  {
    id: "eq-011",
    name: "İş İstasyonu #2",
    model: "İş İstasyonu",
    category: "bilgisayar",
    status: "musait",
    ownership: "sahip",
  },
  {
    id: "eq-012",
    name: "İş İstasyonu #3",
    model: "İş İstasyonu",
    category: "bilgisayar",
    status: "musait",
    ownership: "sahip",
  },
  {
    id: "eq-013",
    name: "İş İstasyonu #4",
    model: "İş İstasyonu",
    category: "bilgisayar",
    status: "musait",
    ownership: "sahip",
  },
];

export const SEED_SOFTWARE: Software[] = [
  {
    id: "sw-001",
    name: "Agisoft Metashape",
    licenseType: "perpetual",
    notes: "Fotogrametri ve nokta bulutu işleme.",
  },
  {
    id: "sw-002",
    name: "Bentley iTwin Capture",
    licenseType: "subscription",
    notes: "Fotogrametri ve 3D modelleme.",
  },
  {
    id: "sw-003",
    name: "Pix4D",
    licenseType: "subscription",
    notes: "Drone görüntü işleme ve haritalama.",
  },
  {
    id: "sw-004",
    name: "DJI Terra",
    licenseType: "perpetual",
    notes: "DJI drone veri işleme.",
  },
  {
    id: "sw-005",
    name: "QGIS",
    licenseType: "free",
    notes: "Açık kaynak CBS yazılımı.",
  },
  {
    id: "sw-006",
    name: "ArcGIS",
    licenseType: "subscription",
    notes: "Esri CBS platformu.",
  },
  {
    id: "sw-007",
    name: "NetCAD",
    licenseType: "perpetual",
    notes: "Harita ve CBS yazılımı.",
  },
  {
    id: "sw-008",
    name: "AutoCAD",
    licenseType: "subscription",
    notes: "CAD çizim yazılımı.",
  },
  {
    id: "sw-009",
    name: "Blender",
    licenseType: "free",
    notes: "3D modelleme ve görselleştirme.",
  },
  {
    id: "sw-010",
    name: "MicroStation",
    licenseType: "subscription",
    notes: "Bentley CAD yazılımı.",
  },
  {
    id: "sw-011",
    name: "StaticToRinex",
    licenseType: "free",
    notes: "GPS statik veri dönüşümü.",
  },
  {
    id: "sw-012",
    name: "Lixel Studio",
    licenseType: "perpetual",
    notes: "Xgrids veri işleme ve PPK processing.",
  },
  {
    id: "sw-013",
    name: "Lixel Cyber Color",
    licenseType: "perpetual",
    notes: "Nokta bulutu renklendirme.",
  },
  {
    id: "sw-014",
    name: "Cyclone",
    licenseType: "subscription",
    notes: "Leica nokta bulutu işleme.",
  },
];

export const SEED_STORAGE: StorageUnit[] = [
  {
    id: "st-001",
    name: "ihaarsiv",
    totalCapacityTB: 10,
    usedCapacityTB: 0,
    notes: "İHA arşiv depolama sunucusu.",
  },
  {
    id: "st-002",
    name: "cografidrone",
    totalCapacityTB: 60,
    usedCapacityTB: 0,
    notes: "Coğrafi drone veri depolama sunucusu.",
  },
];

export const SEED_TEAM: TeamMember[] = [
  { id: "tm-001", name: "Personel 1", role: "Ekip Üyesi" },
  { id: "tm-002", name: "Personel 2", role: "Ekip Üyesi" },
  { id: "tm-003", name: "Personel 3", role: "Ekip Üyesi" },
  { id: "tm-004", name: "Personel 4", role: "Ekip Üyesi" },
  { id: "tm-005", name: "Personel 5", role: "Ekip Üyesi" },
  { id: "tm-006", name: "Personel 6", role: "Ekip Üyesi" },
  { id: "tm-007", name: "Personel 7", role: "Ekip Üyesi" },
];

export const SEED_OPERATIONS: Operation[] = [];
